// Code generated by sqlc. DO NOT EDIT.

import { generatedInternals as d1_values } from "./runtime";
import type { QueryDescriptor, D1NonNullValue, D1Value, JsonValue } from "./runtime";

type d1_Context = { readonly operation: "execute" | "batch"; readonly queryName: string; readonly batchIndex?: number | undefined; readonly rowIndex?: number | undefined };

const createFeedQuery = "INSERT INTO feeds\n(id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at";

export interface CreateFeedArgs {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateFeedRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseCreateFeedRow(row: Record<string, unknown>, ctx: d1_Context): CreateFeedRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function createFeed(args: CreateFeedArgs): QueryDescriptor<CreateFeedRow | null> {
    d1_values.requireArgs(args, "CreateFeed");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateFeed",
        sql: createFeedQuery,
        params: Object.freeze([d1_values.argText(args["id"], "CreateFeed", "id"), d1_values.argText(args["userId"], "CreateFeed", "userId"), d1_values.argText(args["type"], "CreateFeed", "type"), d1_values.argText(args["title"], "CreateFeed", "title"), d1_values.argText(args["link"], "CreateFeed", "link"), d1_values.argText(args["authors"], "CreateFeed", "authors"), d1_values.argText(args["description"], "CreateFeed", "description"), d1_values.argInteger(args["createdAt"], "CreateFeed", "createdAt"), d1_values.argInteger(args["updatedAt"], "CreateFeed", "updatedAt"), d1_values.argIntegerOrNull(args["deletedAt"], "CreateFeed", "deletedAt")]),
        parse: parseCreateFeedRow
    }) as unknown as QueryDescriptor<CreateFeedRow | null>;
}

const getFeedByIdQuery = "SELECT id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at\nFROM feeds\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFeedByIdArgs {
    "id": string;
}

export interface GetFeedByIdRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFeedByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetFeedByIdRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function getFeedById(args: GetFeedByIdArgs): QueryDescriptor<GetFeedByIdRow | null> {
    d1_values.requireArgs(args, "GetFeedById");
    return Object.freeze({
        kind: "one",
        name: "GetFeedById",
        sql: getFeedByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFeedById", "id")]),
        parse: parseGetFeedByIdRow
    }) as unknown as QueryDescriptor<GetFeedByIdRow | null>;
}

const updateFeedUpdatedAtQuery = "UPDATE feeds\nSET updated_at = ?\nWHERE id = ?";

export interface UpdateFeedUpdatedAtArgs {
    "updatedAt": number;
    "id": string;
}

export function updateFeedUpdatedAt(args: UpdateFeedUpdatedAtArgs): QueryDescriptor<void> {
    d1_values.requireArgs(args, "UpdateFeedUpdatedAt");
    return Object.freeze({
        kind: "exec",
        name: "UpdateFeedUpdatedAt",
        sql: updateFeedUpdatedAtQuery,
        params: Object.freeze([d1_values.argInteger(args["updatedAt"], "UpdateFeedUpdatedAt", "updatedAt"), d1_values.argText(args["id"], "UpdateFeedUpdatedAt", "id")])
    }) as unknown as QueryDescriptor<void>;
}

const createItemQuery = "INSERT INTO items\n(id, feed_id, user_id, file_id, title, description, link, authors, published_at, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at";

export interface CreateItemArgs {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "publishedAt": number;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateItemRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseCreateItemRow(row: Record<string, unknown>, ctx: d1_Context): CreateItemRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx)
    };
}

export function createItem(args: CreateItemArgs): QueryDescriptor<CreateItemRow | null> {
    d1_values.requireArgs(args, "CreateItem");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateItem",
        sql: createItemQuery,
        params: Object.freeze([d1_values.argText(args["id"], "CreateItem", "id"), d1_values.argText(args["feedId"], "CreateItem", "feedId"), d1_values.argText(args["userId"], "CreateItem", "userId"), d1_values.argText(args["fileId"], "CreateItem", "fileId"), d1_values.argText(args["title"], "CreateItem", "title"), d1_values.argText(args["description"], "CreateItem", "description"), d1_values.argText(args["link"], "CreateItem", "link"), d1_values.argText(args["authors"], "CreateItem", "authors"), d1_values.argInteger(args["publishedAt"], "CreateItem", "publishedAt"), d1_values.argInteger(args["createdAt"], "CreateItem", "createdAt"), d1_values.argInteger(args["updatedAt"], "CreateItem", "updatedAt"), d1_values.argIntegerOrNull(args["deletedAt"], "CreateItem", "deletedAt")]),
        parse: parseCreateItemRow
    }) as unknown as QueryDescriptor<CreateItemRow | null>;
}

const getItemsByFeedIdQuery = "SELECT id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at\nFROM items\nWHERE feed_id = ?\n  AND deleted_at IS NULL";

export interface GetItemsByFeedIdArgs {
    "feedId": string;
}

export interface GetItemsByFeedIdRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseGetItemsByFeedIdRow(row: Record<string, unknown>, ctx: d1_Context): GetItemsByFeedIdRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx)
    };
}

export function getItemsByFeedId(args: GetItemsByFeedIdArgs): QueryDescriptor<GetItemsByFeedIdRow[]> {
    d1_values.requireArgs(args, "GetItemsByFeedId");
    return Object.freeze({
        kind: "many",
        name: "GetItemsByFeedId",
        sql: getItemsByFeedIdQuery,
        params: Object.freeze([d1_values.argText(args["feedId"], "GetItemsByFeedId", "feedId")]),
        parse: parseGetItemsByFeedIdRow
    }) as unknown as QueryDescriptor<GetItemsByFeedIdRow[]>;
}

const createFileQuery = "INSERT INTO files\n(id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at";

export interface CreateFileArgs {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateFileRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseCreateFileRow(row: Record<string, unknown>, ctx: d1_Context): CreateFileRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "itemId": d1_values.rowTextOrNull(row, "item_id", "itemId", ctx),
        "size": d1_values.rowInteger(row, "size", "size", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "hash": d1_values.rowText(row, "hash", "hash", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function createFile(args: CreateFileArgs): QueryDescriptor<CreateFileRow | null> {
    d1_values.requireArgs(args, "CreateFile");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateFile",
        sql: createFileQuery,
        params: Object.freeze([d1_values.argText(args["id"], "CreateFile", "id"), d1_values.argText(args["userId"], "CreateFile", "userId"), d1_values.argTextOrNull(args["itemId"], "CreateFile", "itemId"), d1_values.argInteger(args["size"], "CreateFile", "size"), d1_values.argText(args["mimeType"], "CreateFile", "mimeType"), d1_values.argText(args["hash"], "CreateFile", "hash"), d1_values.argText(args["uploadUrl"], "CreateFile", "uploadUrl"), d1_values.argInteger(args["createdAt"], "CreateFile", "createdAt"), d1_values.argInteger(args["updatedAt"], "CreateFile", "updatedAt"), d1_values.argIntegerOrNull(args["deletedAt"], "CreateFile", "deletedAt")]),
        parse: parseCreateFileRow
    }) as unknown as QueryDescriptor<CreateFileRow | null>;
}

const updateFileItemIdQuery = "UPDATE files\nSET item_id = ?\nWHERE id = ?";

export interface UpdateFileItemIdArgs {
    "itemId": string | null;
    "id": string;
}

export function updateFileItemId(args: UpdateFileItemIdArgs): QueryDescriptor<void> {
    d1_values.requireArgs(args, "UpdateFileItemId");
    return Object.freeze({
        kind: "exec",
        name: "UpdateFileItemId",
        sql: updateFileItemIdQuery,
        params: Object.freeze([d1_values.argTextOrNull(args["itemId"], "UpdateFileItemId", "itemId"), d1_values.argText(args["id"], "UpdateFileItemId", "id")])
    }) as unknown as QueryDescriptor<void>;
}

const getFileByIdQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFileByIdArgs {
    "id": string;
}

export interface GetFileByIdRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFileByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetFileByIdRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "itemId": d1_values.rowTextOrNull(row, "item_id", "itemId", ctx),
        "size": d1_values.rowInteger(row, "size", "size", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "hash": d1_values.rowText(row, "hash", "hash", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function getFileById(args: GetFileByIdArgs): QueryDescriptor<GetFileByIdRow | null> {
    d1_values.requireArgs(args, "GetFileById");
    return Object.freeze({
        kind: "one",
        name: "GetFileById",
        sql: getFileByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFileById", "id")]),
        parse: parseGetFileByIdRow
    }) as unknown as QueryDescriptor<GetFileByIdRow | null>;
}

const listFilesQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE deleted_at IS NULL\nORDER BY created_at DESC";

export interface ListFilesRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseListFilesRow(row: Record<string, unknown>, ctx: d1_Context): ListFilesRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "itemId": d1_values.rowTextOrNull(row, "item_id", "itemId", ctx),
        "size": d1_values.rowInteger(row, "size", "size", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "hash": d1_values.rowText(row, "hash", "hash", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function listFiles(): QueryDescriptor<ListFilesRow[]> {
    return Object.freeze({
        kind: "many",
        name: "ListFiles",
        sql: listFilesQuery,
        params: Object.freeze([]),
        parse: parseListFilesRow
    }) as unknown as QueryDescriptor<ListFilesRow[]>;
}

const getFileByIdForUserQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE id = ?\n  AND user_id = ?\n  AND deleted_at IS NULL";

export interface GetFileByIdForUserArgs {
    "id": string;
    "userId": string;
}

export interface GetFileByIdForUserRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFileByIdForUserRow(row: Record<string, unknown>, ctx: d1_Context): GetFileByIdForUserRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "itemId": d1_values.rowTextOrNull(row, "item_id", "itemId", ctx),
        "size": d1_values.rowInteger(row, "size", "size", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "hash": d1_values.rowText(row, "hash", "hash", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function getFileByIdForUser(args: GetFileByIdForUserArgs): QueryDescriptor<GetFileByIdForUserRow | null> {
    d1_values.requireArgs(args, "GetFileByIdForUser");
    return Object.freeze({
        kind: "one",
        name: "GetFileByIdForUser",
        sql: getFileByIdForUserQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFileByIdForUser", "id"), d1_values.argText(args["userId"], "GetFileByIdForUser", "userId")]),
        parse: parseGetFileByIdForUserRow
    }) as unknown as QueryDescriptor<GetFileByIdForUserRow | null>;
}

const getItemsWithFilesByFeedIdQuery = "SELECT i.id          as item_id,\n       i.feed_id,\n       i.user_id,\n       i.file_id,\n       i.title       as item_title,\n       i.description as item_description,\n       i.link        as item_link,\n       i.authors     as item_authors,\n       i.published_at,\n       i.created_at  as item_created_at,\n       i.updated_at  as item_updated_at,\n       f.id          as joined_file_id,\n       f.size        as file_size,\n       f.mime_type,\n       f.upload_url\nFROM items i\n         JOIN files f ON i.file_id = f.id\nWHERE i.feed_id = ?\n  AND i.deleted_at IS NULL\n  AND f.deleted_at IS NULL\nORDER BY i.published_at DESC";

export interface GetItemsWithFilesByFeedIdArgs {
    "feedId": string;
}

export interface GetItemsWithFilesByFeedIdRow {
    "itemId": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "itemTitle": string;
    "itemDescription": string;
    "itemLink": string;
    "itemAuthors": string;
    "publishedAt": number;
    "itemCreatedAt": number;
    "itemUpdatedAt": number;
    "joinedFileId": string;
    "fileSize": number;
    "mimeType": string;
    "uploadUrl": string;
}

function parseGetItemsWithFilesByFeedIdRow(row: Record<string, unknown>, ctx: d1_Context): GetItemsWithFilesByFeedIdRow {
    return {
        "itemId": d1_values.rowText(row, "item_id", "itemId", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "itemTitle": d1_values.rowText(row, "item_title", "itemTitle", ctx),
        "itemDescription": d1_values.rowText(row, "item_description", "itemDescription", ctx),
        "itemLink": d1_values.rowText(row, "item_link", "itemLink", ctx),
        "itemAuthors": d1_values.rowText(row, "item_authors", "itemAuthors", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx),
        "itemCreatedAt": d1_values.rowInteger(row, "item_created_at", "itemCreatedAt", ctx),
        "itemUpdatedAt": d1_values.rowInteger(row, "item_updated_at", "itemUpdatedAt", ctx),
        "joinedFileId": d1_values.rowText(row, "joined_file_id", "joinedFileId", ctx),
        "fileSize": d1_values.rowInteger(row, "file_size", "fileSize", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx)
    };
}

export function getItemsWithFilesByFeedId(args: GetItemsWithFilesByFeedIdArgs): QueryDescriptor<GetItemsWithFilesByFeedIdRow[]> {
    d1_values.requireArgs(args, "GetItemsWithFilesByFeedId");
    return Object.freeze({
        kind: "many",
        name: "GetItemsWithFilesByFeedId",
        sql: getItemsWithFilesByFeedIdQuery,
        params: Object.freeze([d1_values.argText(args["feedId"], "GetItemsWithFilesByFeedId", "feedId")]),
        parse: parseGetItemsWithFilesByFeedIdRow
    }) as unknown as QueryDescriptor<GetItemsWithFilesByFeedIdRow[]>;
}

const getItemWithFileByIdQuery = "SELECT i.id          as item_id,\n       i.feed_id,\n       i.user_id,\n       i.file_id,\n       i.title       as item_title,\n       i.description as item_description,\n       i.link        as item_link,\n       i.authors     as item_authors,\n       i.published_at,\n       i.created_at  as item_created_at,\n       i.updated_at  as item_updated_at,\n       f.size        as file_size,\n       f.mime_type,\n       f.upload_url\nFROM items i\n         JOIN files f ON i.file_id = f.id\nWHERE i.id = ?\n  AND i.deleted_at IS NULL\n  AND f.deleted_at IS NULL";

export interface GetItemWithFileByIdArgs {
    "id": string;
}

export interface GetItemWithFileByIdRow {
    "itemId": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "itemTitle": string;
    "itemDescription": string;
    "itemLink": string;
    "itemAuthors": string;
    "publishedAt": number;
    "itemCreatedAt": number;
    "itemUpdatedAt": number;
    "fileSize": number;
    "mimeType": string;
    "uploadUrl": string;
}

function parseGetItemWithFileByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetItemWithFileByIdRow {
    return {
        "itemId": d1_values.rowText(row, "item_id", "itemId", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "itemTitle": d1_values.rowText(row, "item_title", "itemTitle", ctx),
        "itemDescription": d1_values.rowText(row, "item_description", "itemDescription", ctx),
        "itemLink": d1_values.rowText(row, "item_link", "itemLink", ctx),
        "itemAuthors": d1_values.rowText(row, "item_authors", "itemAuthors", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx),
        "itemCreatedAt": d1_values.rowInteger(row, "item_created_at", "itemCreatedAt", ctx),
        "itemUpdatedAt": d1_values.rowInteger(row, "item_updated_at", "itemUpdatedAt", ctx),
        "fileSize": d1_values.rowInteger(row, "file_size", "fileSize", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx)
    };
}

export function getItemWithFileById(args: GetItemWithFileByIdArgs): QueryDescriptor<GetItemWithFileByIdRow | null> {
    d1_values.requireArgs(args, "GetItemWithFileById");
    return Object.freeze({
        kind: "one",
        name: "GetItemWithFileById",
        sql: getItemWithFileByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetItemWithFileById", "id")]),
        parse: parseGetItemWithFileByIdRow
    }) as unknown as QueryDescriptor<GetItemWithFileByIdRow | null>;
}

const getItemByIdQuery = "SELECT id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at\nFROM items\nWHERE id = ?\n  AND feed_id = ?\n  AND deleted_at IS NULL";

export interface GetItemByIdArgs {
    "id": string;
    "feedId": string;
}

export interface GetItemByIdRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseGetItemByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetItemByIdRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx)
    };
}

export function getItemById(args: GetItemByIdArgs): QueryDescriptor<GetItemByIdRow | null> {
    d1_values.requireArgs(args, "GetItemById");
    return Object.freeze({
        kind: "one",
        name: "GetItemById",
        sql: getItemByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetItemById", "id"), d1_values.argText(args["feedId"], "GetItemById", "feedId")]),
        parse: parseGetItemByIdRow
    }) as unknown as QueryDescriptor<GetItemByIdRow | null>;
}

const getFeedUserByIdQuery = "SELECT user_id\nFROM feeds\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFeedUserByIdArgs {
    "id": string;
}

export interface GetFeedUserByIdRow {
    "userId": string;
}

function parseGetFeedUserByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetFeedUserByIdRow {
    return {
        "userId": d1_values.rowText(row, "user_id", "userId", ctx)
    };
}

export function getFeedUserById(args: GetFeedUserByIdArgs): QueryDescriptor<GetFeedUserByIdRow | null> {
    d1_values.requireArgs(args, "GetFeedUserById");
    return Object.freeze({
        kind: "one",
        name: "GetFeedUserById",
        sql: getFeedUserByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFeedUserById", "id")]),
        parse: parseGetFeedUserByIdRow
    }) as unknown as QueryDescriptor<GetFeedUserByIdRow | null>;
}

const updateItemByIdQuery = "UPDATE items\nSET title        = ?,\n    description  = ?,\n    link         = ?,\n    authors      = ?,\n    published_at = ?,\n    updated_at   = ?\nWHERE id = ?\n  AND feed_id = ?";

export interface UpdateItemByIdArgs {
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "publishedAt": number;
    "updatedAt": number;
    "id": string;
    "feedId": string;
}

export function updateItemById(args: UpdateItemByIdArgs): QueryDescriptor<void> {
    d1_values.requireArgs(args, "UpdateItemById");
    return Object.freeze({
        kind: "exec",
        name: "UpdateItemById",
        sql: updateItemByIdQuery,
        params: Object.freeze([d1_values.argText(args["title"], "UpdateItemById", "title"), d1_values.argText(args["description"], "UpdateItemById", "description"), d1_values.argText(args["link"], "UpdateItemById", "link"), d1_values.argText(args["authors"], "UpdateItemById", "authors"), d1_values.argInteger(args["publishedAt"], "UpdateItemById", "publishedAt"), d1_values.argInteger(args["updatedAt"], "UpdateItemById", "updatedAt"), d1_values.argText(args["id"], "UpdateItemById", "id"), d1_values.argText(args["feedId"], "UpdateItemById", "feedId")])
    }) as unknown as QueryDescriptor<void>;
}

const createSampleQuery = "INSERT INTO samples\n(int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null,\n json_value, json_null, any_value, any_null)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null";

export interface CreateSampleArgs {
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": JsonValue;
    "jsonNull": JsonValue | null;
    "anyValue": D1NonNullValue;
    "anyNull": D1Value;
}

export interface CreateSampleRow {
    "id": number;
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": unknown;
    "jsonNull": unknown;
    "anyValue": unknown;
    "anyNull": unknown;
}

function parseCreateSampleRow(row: Record<string, unknown>, ctx: d1_Context): CreateSampleRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "intValue": d1_values.rowInteger(row, "int_value", "intValue", ctx),
        "intNull": d1_values.rowIntegerOrNull(row, "int_null", "intNull", ctx),
        "numValue": d1_values.rowNumber(row, "num_value", "numValue", ctx),
        "numNull": d1_values.rowNumberOrNull(row, "num_null", "numNull", ctx),
        "textValue": d1_values.rowText(row, "text_value", "textValue", ctx),
        "textNull": d1_values.rowTextOrNull(row, "text_null", "textNull", ctx),
        "boolValue": d1_values.rowBoolean(row, "bool_value", "boolValue", ctx),
        "boolNull": d1_values.rowBooleanOrNull(row, "bool_null", "boolNull", ctx),
        "blobValue": d1_values.rowBlob(row, "blob_value", "blobValue", ctx),
        "blobNull": d1_values.rowBlobOrNull(row, "blob_null", "blobNull", ctx),
        "jsonValue": d1_values.rowJson(row, "json_value", "jsonValue", ctx),
        "jsonNull": d1_values.rowJsonOrNull(row, "json_null", "jsonNull", ctx),
        "anyValue": d1_values.rowUnknown(row, "any_value", "anyValue", ctx),
        "anyNull": d1_values.rowUnknownOrNull(row, "any_null", "anyNull", ctx)
    };
}

export function createSample(args: CreateSampleArgs): QueryDescriptor<CreateSampleRow | null> {
    d1_values.requireArgs(args, "CreateSample");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateSample",
        sql: createSampleQuery,
        params: Object.freeze([d1_values.argInteger(args["intValue"], "CreateSample", "intValue"), d1_values.argIntegerOrNull(args["intNull"], "CreateSample", "intNull"), d1_values.argNumber(args["numValue"], "CreateSample", "numValue"), d1_values.argNumberOrNull(args["numNull"], "CreateSample", "numNull"), d1_values.argText(args["textValue"], "CreateSample", "textValue"), d1_values.argTextOrNull(args["textNull"], "CreateSample", "textNull"), d1_values.argBoolean(args["boolValue"], "CreateSample", "boolValue"), d1_values.argBooleanOrNull(args["boolNull"], "CreateSample", "boolNull"), d1_values.argBlob(args["blobValue"], "CreateSample", "blobValue"), d1_values.argBlobOrNull(args["blobNull"], "CreateSample", "blobNull"), d1_values.argJson(args["jsonValue"], "CreateSample", "jsonValue"), d1_values.argJsonOrNull(args["jsonNull"], "CreateSample", "jsonNull"), d1_values.argUnknown(args["anyValue"], "CreateSample", "anyValue"), d1_values.argUnknownOrNull(args["anyNull"], "CreateSample", "anyNull")]),
        parse: parseCreateSampleRow
    }) as unknown as QueryDescriptor<CreateSampleRow | null>;
}

const getSampleByIdQuery = "SELECT id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null\nFROM samples\nWHERE id = ?";

export interface GetSampleByIdArgs {
    "id": number;
}

export interface GetSampleByIdRow {
    "id": number;
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": unknown;
    "jsonNull": unknown;
    "anyValue": unknown;
    "anyNull": unknown;
}

function parseGetSampleByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetSampleByIdRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "intValue": d1_values.rowInteger(row, "int_value", "intValue", ctx),
        "intNull": d1_values.rowIntegerOrNull(row, "int_null", "intNull", ctx),
        "numValue": d1_values.rowNumber(row, "num_value", "numValue", ctx),
        "numNull": d1_values.rowNumberOrNull(row, "num_null", "numNull", ctx),
        "textValue": d1_values.rowText(row, "text_value", "textValue", ctx),
        "textNull": d1_values.rowTextOrNull(row, "text_null", "textNull", ctx),
        "boolValue": d1_values.rowBoolean(row, "bool_value", "boolValue", ctx),
        "boolNull": d1_values.rowBooleanOrNull(row, "bool_null", "boolNull", ctx),
        "blobValue": d1_values.rowBlob(row, "blob_value", "blobValue", ctx),
        "blobNull": d1_values.rowBlobOrNull(row, "blob_null", "blobNull", ctx),
        "jsonValue": d1_values.rowJson(row, "json_value", "jsonValue", ctx),
        "jsonNull": d1_values.rowJsonOrNull(row, "json_null", "jsonNull", ctx),
        "anyValue": d1_values.rowUnknown(row, "any_value", "anyValue", ctx),
        "anyNull": d1_values.rowUnknownOrNull(row, "any_null", "anyNull", ctx)
    };
}

export function getSampleById(args: GetSampleByIdArgs): QueryDescriptor<GetSampleByIdRow | null> {
    d1_values.requireArgs(args, "GetSampleById");
    return Object.freeze({
        kind: "one",
        name: "GetSampleById",
        sql: getSampleByIdQuery,
        params: Object.freeze([d1_values.argInteger(args["id"], "GetSampleById", "id")]),
        parse: parseGetSampleByIdRow
    }) as unknown as QueryDescriptor<GetSampleByIdRow | null>;
}

const listSamplesQuery = "SELECT id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null\nFROM samples\nORDER BY id";

export interface ListSamplesRow {
    "id": number;
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": unknown;
    "jsonNull": unknown;
    "anyValue": unknown;
    "anyNull": unknown;
}

function parseListSamplesRow(row: Record<string, unknown>, ctx: d1_Context): ListSamplesRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "intValue": d1_values.rowInteger(row, "int_value", "intValue", ctx),
        "intNull": d1_values.rowIntegerOrNull(row, "int_null", "intNull", ctx),
        "numValue": d1_values.rowNumber(row, "num_value", "numValue", ctx),
        "numNull": d1_values.rowNumberOrNull(row, "num_null", "numNull", ctx),
        "textValue": d1_values.rowText(row, "text_value", "textValue", ctx),
        "textNull": d1_values.rowTextOrNull(row, "text_null", "textNull", ctx),
        "boolValue": d1_values.rowBoolean(row, "bool_value", "boolValue", ctx),
        "boolNull": d1_values.rowBooleanOrNull(row, "bool_null", "boolNull", ctx),
        "blobValue": d1_values.rowBlob(row, "blob_value", "blobValue", ctx),
        "blobNull": d1_values.rowBlobOrNull(row, "blob_null", "blobNull", ctx),
        "jsonValue": d1_values.rowJson(row, "json_value", "jsonValue", ctx),
        "jsonNull": d1_values.rowJsonOrNull(row, "json_null", "jsonNull", ctx),
        "anyValue": d1_values.rowUnknown(row, "any_value", "anyValue", ctx),
        "anyNull": d1_values.rowUnknownOrNull(row, "any_null", "anyNull", ctx)
    };
}

export function listSamples(): QueryDescriptor<ListSamplesRow[]> {
    return Object.freeze({
        kind: "many",
        name: "ListSamples",
        sql: listSamplesQuery,
        params: Object.freeze([]),
        parse: parseListSamplesRow
    }) as unknown as QueryDescriptor<ListSamplesRow[]>;
}

const createQuirkQuery = "INSERT INTO quirks (id)\nVALUES (?)\nRETURNING id, flag";

export interface CreateQuirkArgs {
    "id": number;
}

export interface CreateQuirkRow {
    "id": number;
    "flag": boolean;
}

function parseCreateQuirkRow(row: Record<string, unknown>, ctx: d1_Context): CreateQuirkRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "flag": d1_values.rowBoolean(row, "flag", "flag", ctx)
    };
}

export function createQuirk(args: CreateQuirkArgs): QueryDescriptor<CreateQuirkRow | null> {
    d1_values.requireArgs(args, "CreateQuirk");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateQuirk",
        sql: createQuirkQuery,
        params: Object.freeze([d1_values.argInteger(args["id"], "CreateQuirk", "id")]),
        parse: parseCreateQuirkRow
    }) as unknown as QueryDescriptor<CreateQuirkRow | null>;
}
