// Code generated by sqlc. DO NOT EDIT.

import type { OneQuery, OneInsertQuery, ManyQuery, ExecQuery } from "./runtime";

const createFeedQuery = "INSERT INTO feeds\n(id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at";

export interface CreateFeedArgs {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateFeedRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseCreateFeedRow(row: Record<string, unknown>): CreateFeedRow {
    return {
        "id": row["id"] as string,
        "userId": row["user_id"] as string,
        "type": row["type"] as string,
        "title": row["title"] as string,
        "link": row["link"] as string,
        "authors": row["authors"] as string,
        "description": row["description"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null
    };
}

export function createFeed(args: CreateFeedArgs): OneInsertQuery<CreateFeedRow> {
    return {
        kind: "one-insert",
        sql: createFeedQuery,
        params: [args["id"], args["userId"], args["type"], args["title"], args["link"], args["authors"], args["description"], args["createdAt"], args["updatedAt"], args["deletedAt"]],
        parse: parseCreateFeedRow
    };
}

const getFeedByIdQuery = "SELECT id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at\nFROM feeds\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFeedByIdArgs {
    "id": string;
}

export interface GetFeedByIdRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFeedByIdRow(row: Record<string, unknown>): GetFeedByIdRow {
    return {
        "id": row["id"] as string,
        "userId": row["user_id"] as string,
        "type": row["type"] as string,
        "title": row["title"] as string,
        "link": row["link"] as string,
        "authors": row["authors"] as string,
        "description": row["description"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null
    };
}

export function getFeedById(args: GetFeedByIdArgs): OneQuery<GetFeedByIdRow> {
    return {
        kind: "one",
        sql: getFeedByIdQuery,
        params: [args["id"]],
        parse: parseGetFeedByIdRow
    };
}

const updateFeedUpdatedAtQuery = "UPDATE feeds\nSET updated_at = ?\nWHERE id = ?";

export interface UpdateFeedUpdatedAtArgs {
    "updatedAt": number;
    "id": string;
}

export function updateFeedUpdatedAt(args: UpdateFeedUpdatedAtArgs): ExecQuery {
    return {
        kind: "exec",
        sql: updateFeedUpdatedAtQuery,
        params: [args["updatedAt"], args["id"]]
    };
}

const createItemQuery = "INSERT INTO items\n(id, feed_id, user_id, file_id, title, description, link, authors, published_at, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at";

export interface CreateItemArgs {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "publishedAt": number;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateItemRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseCreateItemRow(row: Record<string, unknown>): CreateItemRow {
    return {
        "id": row["id"] as string,
        "feedId": row["feed_id"] as string,
        "userId": row["user_id"] as string,
        "fileId": row["file_id"] as string,
        "title": row["title"] as string,
        "description": row["description"] as string,
        "link": row["link"] as string,
        "authors": row["authors"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null,
        "publishedAt": row["published_at"] as number
    };
}

export function createItem(args: CreateItemArgs): OneInsertQuery<CreateItemRow> {
    return {
        kind: "one-insert",
        sql: createItemQuery,
        params: [args["id"], args["feedId"], args["userId"], args["fileId"], args["title"], args["description"], args["link"], args["authors"], args["publishedAt"], args["createdAt"], args["updatedAt"], args["deletedAt"]],
        parse: parseCreateItemRow
    };
}

const getItemsByFeedIdQuery = "SELECT id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at\nFROM items\nWHERE feed_id = ?\n  AND deleted_at IS NULL";

export interface GetItemsByFeedIdArgs {
    "feedId": string;
}

export interface GetItemsByFeedIdRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseGetItemsByFeedIdRow(row: Record<string, unknown>): GetItemsByFeedIdRow {
    return {
        "id": row["id"] as string,
        "feedId": row["feed_id"] as string,
        "userId": row["user_id"] as string,
        "fileId": row["file_id"] as string,
        "title": row["title"] as string,
        "description": row["description"] as string,
        "link": row["link"] as string,
        "authors": row["authors"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null,
        "publishedAt": row["published_at"] as number
    };
}

export function getItemsByFeedId(args: GetItemsByFeedIdArgs): ManyQuery<GetItemsByFeedIdRow> {
    return {
        kind: "many",
        sql: getItemsByFeedIdQuery,
        params: [args["feedId"]],
        parse: parseGetItemsByFeedIdRow
    };
}

const createFileQuery = "INSERT INTO files\n(id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at";

export interface CreateFileArgs {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateFileRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseCreateFileRow(row: Record<string, unknown>): CreateFileRow {
    return {
        "id": row["id"] as string,
        "userId": row["user_id"] as string,
        "itemId": row["item_id"] as string | null,
        "size": row["size"] as number,
        "mimeType": row["mime_type"] as string,
        "hash": row["hash"] as string,
        "uploadUrl": row["upload_url"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null
    };
}

export function createFile(args: CreateFileArgs): OneInsertQuery<CreateFileRow> {
    return {
        kind: "one-insert",
        sql: createFileQuery,
        params: [args["id"], args["userId"], args["itemId"], args["size"], args["mimeType"], args["hash"], args["uploadUrl"], args["createdAt"], args["updatedAt"], args["deletedAt"]],
        parse: parseCreateFileRow
    };
}

const updateFileItemIdQuery = "UPDATE files\nSET item_id = ?\nWHERE id = ?";

export interface UpdateFileItemIdArgs {
    "itemId": string | null;
    "id": string;
}

export function updateFileItemId(args: UpdateFileItemIdArgs): ExecQuery {
    return {
        kind: "exec",
        sql: updateFileItemIdQuery,
        params: [args["itemId"], args["id"]]
    };
}

const getFileByIdQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFileByIdArgs {
    "id": string;
}

export interface GetFileByIdRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFileByIdRow(row: Record<string, unknown>): GetFileByIdRow {
    return {
        "id": row["id"] as string,
        "userId": row["user_id"] as string,
        "itemId": row["item_id"] as string | null,
        "size": row["size"] as number,
        "mimeType": row["mime_type"] as string,
        "hash": row["hash"] as string,
        "uploadUrl": row["upload_url"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null
    };
}

export function getFileById(args: GetFileByIdArgs): OneQuery<GetFileByIdRow> {
    return {
        kind: "one",
        sql: getFileByIdQuery,
        params: [args["id"]],
        parse: parseGetFileByIdRow
    };
}

const listFilesQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE deleted_at IS NULL\nORDER BY created_at DESC";

export interface ListFilesRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseListFilesRow(row: Record<string, unknown>): ListFilesRow {
    return {
        "id": row["id"] as string,
        "userId": row["user_id"] as string,
        "itemId": row["item_id"] as string | null,
        "size": row["size"] as number,
        "mimeType": row["mime_type"] as string,
        "hash": row["hash"] as string,
        "uploadUrl": row["upload_url"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null
    };
}

export function listFiles(): ManyQuery<ListFilesRow> {
    return {
        kind: "many",
        sql: listFilesQuery,
        params: [],
        parse: parseListFilesRow
    };
}

const getFileByIdForUserQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE id = ?\n  AND user_id = ?\n  AND deleted_at IS NULL";

export interface GetFileByIdForUserArgs {
    "id": string;
    "userId": string;
}

export interface GetFileByIdForUserRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFileByIdForUserRow(row: Record<string, unknown>): GetFileByIdForUserRow {
    return {
        "id": row["id"] as string,
        "userId": row["user_id"] as string,
        "itemId": row["item_id"] as string | null,
        "size": row["size"] as number,
        "mimeType": row["mime_type"] as string,
        "hash": row["hash"] as string,
        "uploadUrl": row["upload_url"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null
    };
}

export function getFileByIdForUser(args: GetFileByIdForUserArgs): OneQuery<GetFileByIdForUserRow> {
    return {
        kind: "one",
        sql: getFileByIdForUserQuery,
        params: [args["id"], args["userId"]],
        parse: parseGetFileByIdForUserRow
    };
}

const getItemsWithFilesByFeedIdQuery = "SELECT i.id          as item_id,\n       i.feed_id,\n       i.user_id,\n       i.file_id,\n       i.title       as item_title,\n       i.description as item_description,\n       i.link        as item_link,\n       i.authors     as item_authors,\n       i.published_at,\n       i.created_at  as item_created_at,\n       i.updated_at  as item_updated_at,\n       f.id          as joined_file_id,\n       f.size        as file_size,\n       f.mime_type,\n       f.upload_url\nFROM items i\n         JOIN files f ON i.file_id = f.id\nWHERE i.feed_id = ?\n  AND i.deleted_at IS NULL\n  AND f.deleted_at IS NULL\nORDER BY i.published_at DESC";

export interface GetItemsWithFilesByFeedIdArgs {
    "feedId": string;
}

export interface GetItemsWithFilesByFeedIdRow {
    "itemId": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "itemTitle": string;
    "itemDescription": string;
    "itemLink": string;
    "itemAuthors": string;
    "publishedAt": number;
    "itemCreatedAt": number;
    "itemUpdatedAt": number;
    "joinedFileId": string;
    "fileSize": number;
    "mimeType": string;
    "uploadUrl": string;
}

function parseGetItemsWithFilesByFeedIdRow(row: Record<string, unknown>): GetItemsWithFilesByFeedIdRow {
    return {
        "itemId": row["item_id"] as string,
        "feedId": row["feed_id"] as string,
        "userId": row["user_id"] as string,
        "fileId": row["file_id"] as string,
        "itemTitle": row["item_title"] as string,
        "itemDescription": row["item_description"] as string,
        "itemLink": row["item_link"] as string,
        "itemAuthors": row["item_authors"] as string,
        "publishedAt": row["published_at"] as number,
        "itemCreatedAt": row["item_created_at"] as number,
        "itemUpdatedAt": row["item_updated_at"] as number,
        "joinedFileId": row["joined_file_id"] as string,
        "fileSize": row["file_size"] as number,
        "mimeType": row["mime_type"] as string,
        "uploadUrl": row["upload_url"] as string
    };
}

export function getItemsWithFilesByFeedId(args: GetItemsWithFilesByFeedIdArgs): ManyQuery<GetItemsWithFilesByFeedIdRow> {
    return {
        kind: "many",
        sql: getItemsWithFilesByFeedIdQuery,
        params: [args["feedId"]],
        parse: parseGetItemsWithFilesByFeedIdRow
    };
}

const getItemWithFileByIdQuery = "SELECT i.id          as item_id,\n       i.feed_id,\n       i.user_id,\n       i.file_id,\n       i.title       as item_title,\n       i.description as item_description,\n       i.link        as item_link,\n       i.authors     as item_authors,\n       i.published_at,\n       i.created_at  as item_created_at,\n       i.updated_at  as item_updated_at,\n       f.size        as file_size,\n       f.mime_type,\n       f.upload_url\nFROM items i\n         JOIN files f ON i.file_id = f.id\nWHERE i.id = ?\n  AND i.deleted_at IS NULL\n  AND f.deleted_at IS NULL";

export interface GetItemWithFileByIdArgs {
    "id": string;
}

export interface GetItemWithFileByIdRow {
    "itemId": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "itemTitle": string;
    "itemDescription": string;
    "itemLink": string;
    "itemAuthors": string;
    "publishedAt": number;
    "itemCreatedAt": number;
    "itemUpdatedAt": number;
    "fileSize": number;
    "mimeType": string;
    "uploadUrl": string;
}

function parseGetItemWithFileByIdRow(row: Record<string, unknown>): GetItemWithFileByIdRow {
    return {
        "itemId": row["item_id"] as string,
        "feedId": row["feed_id"] as string,
        "userId": row["user_id"] as string,
        "fileId": row["file_id"] as string,
        "itemTitle": row["item_title"] as string,
        "itemDescription": row["item_description"] as string,
        "itemLink": row["item_link"] as string,
        "itemAuthors": row["item_authors"] as string,
        "publishedAt": row["published_at"] as number,
        "itemCreatedAt": row["item_created_at"] as number,
        "itemUpdatedAt": row["item_updated_at"] as number,
        "fileSize": row["file_size"] as number,
        "mimeType": row["mime_type"] as string,
        "uploadUrl": row["upload_url"] as string
    };
}

export function getItemWithFileById(args: GetItemWithFileByIdArgs): OneQuery<GetItemWithFileByIdRow> {
    return {
        kind: "one",
        sql: getItemWithFileByIdQuery,
        params: [args["id"]],
        parse: parseGetItemWithFileByIdRow
    };
}

const getItemByIdQuery = "SELECT id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at\nFROM items\nWHERE id = ?\n  AND feed_id = ?\n  AND deleted_at IS NULL";

export interface GetItemByIdArgs {
    "id": string;
    "feedId": string;
}

export interface GetItemByIdRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseGetItemByIdRow(row: Record<string, unknown>): GetItemByIdRow {
    return {
        "id": row["id"] as string,
        "feedId": row["feed_id"] as string,
        "userId": row["user_id"] as string,
        "fileId": row["file_id"] as string,
        "title": row["title"] as string,
        "description": row["description"] as string,
        "link": row["link"] as string,
        "authors": row["authors"] as string,
        "createdAt": row["created_at"] as number,
        "updatedAt": row["updated_at"] as number,
        "deletedAt": row["deleted_at"] as number | null,
        "publishedAt": row["published_at"] as number
    };
}

export function getItemById(args: GetItemByIdArgs): OneQuery<GetItemByIdRow> {
    return {
        kind: "one",
        sql: getItemByIdQuery,
        params: [args["id"], args["feedId"]],
        parse: parseGetItemByIdRow
    };
}

const getFeedUserByIdQuery = "SELECT user_id\nFROM feeds\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFeedUserByIdArgs {
    "id": string;
}

export interface GetFeedUserByIdRow {
    "userId": string;
}

function parseGetFeedUserByIdRow(row: Record<string, unknown>): GetFeedUserByIdRow {
    return {
        "userId": row["user_id"] as string
    };
}

export function getFeedUserById(args: GetFeedUserByIdArgs): OneQuery<GetFeedUserByIdRow> {
    return {
        kind: "one",
        sql: getFeedUserByIdQuery,
        params: [args["id"]],
        parse: parseGetFeedUserByIdRow
    };
}

const updateItemByIdQuery = "UPDATE items\nSET title        = ?,\n    description  = ?,\n    link         = ?,\n    authors      = ?,\n    published_at = ?,\n    updated_at   = ?\nWHERE id = ?\n  AND feed_id = ?";

export interface UpdateItemByIdArgs {
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "publishedAt": number;
    "updatedAt": number;
    "id": string;
    "feedId": string;
}

export function updateItemById(args: UpdateItemByIdArgs): ExecQuery {
    return {
        kind: "exec",
        sql: updateItemByIdQuery,
        params: [args["title"], args["description"], args["link"], args["authors"], args["publishedAt"], args["updatedAt"], args["id"], args["feedId"]]
    };
}
