// Code generated by sqlc. DO NOT EDIT.

import { generatedInternals as d1_values } from "./runtime";
import type { QueryDescriptor } from "./runtime";

type d1_Context = { readonly operation: "execute" | "batch"; readonly queryName: string; readonly batchIndex?: number | undefined; readonly rowIndex?: number | undefined };

const getUserQuery = "SELECT id, name, nickname FROM users WHERE id = ?";

export interface GetUserArgs {
    "id": number;
}

export interface GetUserRow {
    "id": number;
    "name": string;
    "nickname": string | null;
}

function parseGetUserRow(row: Record<string, unknown>, ctx: d1_Context): GetUserRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "name": d1_values.rowText(row, "name", "name", ctx),
        "nickname": d1_values.rowTextOrNull(row, "nickname", "nickname", ctx)
    };
}

export function getUser(args: GetUserArgs): QueryDescriptor<GetUserRow | null> {
    d1_values.requireArgs(args, "GetUser");
    return Object.freeze({
        kind: "one",
        name: "GetUser",
        sql: getUserQuery,
        params: Object.freeze([d1_values.argInteger(args["id"], "GetUser", "id")]),
        parse: parseGetUserRow
    }) as unknown as QueryDescriptor<GetUserRow | null>;
}

const listUsersQuery = "SELECT id, name, nickname FROM users ORDER BY id";

export interface ListUsersRow {
    "id": number;
    "name": string;
    "nickname": string | null;
}

function parseListUsersRow(row: Record<string, unknown>, ctx: d1_Context): ListUsersRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "name": d1_values.rowText(row, "name", "name", ctx),
        "nickname": d1_values.rowTextOrNull(row, "nickname", "nickname", ctx)
    };
}

export function listUsers(): QueryDescriptor<ListUsersRow[]> {
    return Object.freeze({
        kind: "many",
        name: "ListUsers",
        sql: listUsersQuery,
        params: Object.freeze([]),
        parse: parseListUsersRow
    }) as unknown as QueryDescriptor<ListUsersRow[]>;
}

const renameUserQuery = "UPDATE users SET name = ? WHERE id = ? RETURNING id, name, nickname";

export interface RenameUserArgs {
    "name": string;
    "id": number;
}

export interface RenameUserRow {
    "id": number;
    "name": string;
    "nickname": string | null;
}

function parseRenameUserRow(row: Record<string, unknown>, ctx: d1_Context): RenameUserRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "name": d1_values.rowText(row, "name", "name", ctx),
        "nickname": d1_values.rowTextOrNull(row, "nickname", "nickname", ctx)
    };
}

export function renameUser(args: RenameUserArgs): QueryDescriptor<RenameUserRow | null> {
    d1_values.requireArgs(args, "RenameUser");
    return Object.freeze({
        kind: "one",
        name: "RenameUser",
        sql: renameUserQuery,
        params: Object.freeze([d1_values.argText(args["name"], "RenameUser", "name"), d1_values.argInteger(args["id"], "RenameUser", "id")]),
        parse: parseRenameUserRow
    }) as unknown as QueryDescriptor<RenameUserRow | null>;
}
