// Code generated by sqlc. DO NOT EDIT.

import { generatedInternals as d1_values } from "./runtime";
import type { QueryDescriptor, D1NonNullValue, D1Value, JsonValue } from "./runtime";

type d1_Context = { readonly operation: "execute" | "batch"; readonly queryName: string; readonly batchIndex?: number | undefined; readonly rowIndex?: number | undefined };

const createFeedQuery = "INSERT INTO feeds\n(id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at";

export interface CreateFeedArgs {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateFeedRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseCreateFeedRow(row: Record<string, unknown>, ctx: d1_Context): CreateFeedRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function createFeed(args: CreateFeedArgs): QueryDescriptor<CreateFeedRow | null> {
    d1_values.requireArgs(args, "CreateFeed");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateFeed",
        sql: createFeedQuery,
        params: Object.freeze([d1_values.argText(args["id"], "CreateFeed", "id"), d1_values.argText(args["userId"], "CreateFeed", "userId"), d1_values.argText(args["type"], "CreateFeed", "type"), d1_values.argText(args["title"], "CreateFeed", "title"), d1_values.argText(args["link"], "CreateFeed", "link"), d1_values.argText(args["authors"], "CreateFeed", "authors"), d1_values.argText(args["description"], "CreateFeed", "description"), d1_values.argInteger(args["createdAt"], "CreateFeed", "createdAt"), d1_values.argInteger(args["updatedAt"], "CreateFeed", "updatedAt"), d1_values.argIntegerOrNull(args["deletedAt"], "CreateFeed", "deletedAt")]),
        parse: parseCreateFeedRow
    }) as unknown as QueryDescriptor<CreateFeedRow | null>;
}

const getFeedByIdQuery = "SELECT id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at\nFROM feeds\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFeedByIdArgs {
    "id": string;
}

export interface GetFeedByIdRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFeedByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetFeedByIdRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function getFeedById(args: GetFeedByIdArgs): QueryDescriptor<GetFeedByIdRow | null> {
    d1_values.requireArgs(args, "GetFeedById");
    return Object.freeze({
        kind: "one",
        name: "GetFeedById",
        sql: getFeedByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFeedById", "id")]),
        parse: parseGetFeedByIdRow
    }) as unknown as QueryDescriptor<GetFeedByIdRow | null>;
}

const updateFeedUpdatedAtQuery = "UPDATE feeds\nSET updated_at = ?\nWHERE id = ?";

export interface UpdateFeedUpdatedAtArgs {
    "updatedAt": number;
    "id": string;
}

export function updateFeedUpdatedAt(args: UpdateFeedUpdatedAtArgs): QueryDescriptor<void> {
    d1_values.requireArgs(args, "UpdateFeedUpdatedAt");
    return Object.freeze({
        kind: "exec",
        name: "UpdateFeedUpdatedAt",
        sql: updateFeedUpdatedAtQuery,
        params: Object.freeze([d1_values.argInteger(args["updatedAt"], "UpdateFeedUpdatedAt", "updatedAt"), d1_values.argText(args["id"], "UpdateFeedUpdatedAt", "id")])
    }) as unknown as QueryDescriptor<void>;
}

const createItemQuery = "INSERT INTO items\n(id, feed_id, user_id, file_id, title, description, link, authors, published_at, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at";

export interface CreateItemArgs {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "publishedAt": number;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateItemRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseCreateItemRow(row: Record<string, unknown>, ctx: d1_Context): CreateItemRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx)
    };
}

export function createItem(args: CreateItemArgs): QueryDescriptor<CreateItemRow | null> {
    d1_values.requireArgs(args, "CreateItem");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateItem",
        sql: createItemQuery,
        params: Object.freeze([d1_values.argText(args["id"], "CreateItem", "id"), d1_values.argText(args["feedId"], "CreateItem", "feedId"), d1_values.argText(args["userId"], "CreateItem", "userId"), d1_values.argText(args["fileId"], "CreateItem", "fileId"), d1_values.argText(args["title"], "CreateItem", "title"), d1_values.argText(args["description"], "CreateItem", "description"), d1_values.argText(args["link"], "CreateItem", "link"), d1_values.argText(args["authors"], "CreateItem", "authors"), d1_values.argInteger(args["publishedAt"], "CreateItem", "publishedAt"), d1_values.argInteger(args["createdAt"], "CreateItem", "createdAt"), d1_values.argInteger(args["updatedAt"], "CreateItem", "updatedAt"), d1_values.argIntegerOrNull(args["deletedAt"], "CreateItem", "deletedAt")]),
        parse: parseCreateItemRow
    }) as unknown as QueryDescriptor<CreateItemRow | null>;
}

const getItemsByFeedIdQuery = "SELECT id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at\nFROM items\nWHERE feed_id = ?\n  AND deleted_at IS NULL";

export interface GetItemsByFeedIdArgs {
    "feedId": string;
}

export interface GetItemsByFeedIdRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseGetItemsByFeedIdRow(row: Record<string, unknown>, ctx: d1_Context): GetItemsByFeedIdRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx)
    };
}

export function getItemsByFeedId(args: GetItemsByFeedIdArgs): QueryDescriptor<GetItemsByFeedIdRow[]> {
    d1_values.requireArgs(args, "GetItemsByFeedId");
    return Object.freeze({
        kind: "many",
        name: "GetItemsByFeedId",
        sql: getItemsByFeedIdQuery,
        params: Object.freeze([d1_values.argText(args["feedId"], "GetItemsByFeedId", "feedId")]),
        parse: parseGetItemsByFeedIdRow
    }) as unknown as QueryDescriptor<GetItemsByFeedIdRow[]>;
}

const createFileQuery = "INSERT INTO files\n(id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at";

export interface CreateFileArgs {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

export interface CreateFileRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseCreateFileRow(row: Record<string, unknown>, ctx: d1_Context): CreateFileRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "itemId": d1_values.rowTextOrNull(row, "item_id", "itemId", ctx),
        "size": d1_values.rowInteger(row, "size", "size", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "hash": d1_values.rowText(row, "hash", "hash", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function createFile(args: CreateFileArgs): QueryDescriptor<CreateFileRow | null> {
    d1_values.requireArgs(args, "CreateFile");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateFile",
        sql: createFileQuery,
        params: Object.freeze([d1_values.argText(args["id"], "CreateFile", "id"), d1_values.argText(args["userId"], "CreateFile", "userId"), d1_values.argTextOrNull(args["itemId"], "CreateFile", "itemId"), d1_values.argInteger(args["size"], "CreateFile", "size"), d1_values.argText(args["mimeType"], "CreateFile", "mimeType"), d1_values.argText(args["hash"], "CreateFile", "hash"), d1_values.argText(args["uploadUrl"], "CreateFile", "uploadUrl"), d1_values.argInteger(args["createdAt"], "CreateFile", "createdAt"), d1_values.argInteger(args["updatedAt"], "CreateFile", "updatedAt"), d1_values.argIntegerOrNull(args["deletedAt"], "CreateFile", "deletedAt")]),
        parse: parseCreateFileRow
    }) as unknown as QueryDescriptor<CreateFileRow | null>;
}

const updateFileItemIdQuery = "UPDATE files\nSET item_id = ?\nWHERE id = ?";

export interface UpdateFileItemIdArgs {
    "itemId": string | null;
    "id": string;
}

export function updateFileItemId(args: UpdateFileItemIdArgs): QueryDescriptor<void> {
    d1_values.requireArgs(args, "UpdateFileItemId");
    return Object.freeze({
        kind: "exec",
        name: "UpdateFileItemId",
        sql: updateFileItemIdQuery,
        params: Object.freeze([d1_values.argTextOrNull(args["itemId"], "UpdateFileItemId", "itemId"), d1_values.argText(args["id"], "UpdateFileItemId", "id")])
    }) as unknown as QueryDescriptor<void>;
}

const getFileByIdQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFileByIdArgs {
    "id": string;
}

export interface GetFileByIdRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFileByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetFileByIdRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "itemId": d1_values.rowTextOrNull(row, "item_id", "itemId", ctx),
        "size": d1_values.rowInteger(row, "size", "size", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "hash": d1_values.rowText(row, "hash", "hash", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function getFileById(args: GetFileByIdArgs): QueryDescriptor<GetFileByIdRow | null> {
    d1_values.requireArgs(args, "GetFileById");
    return Object.freeze({
        kind: "one",
        name: "GetFileById",
        sql: getFileByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFileById", "id")]),
        parse: parseGetFileByIdRow
    }) as unknown as QueryDescriptor<GetFileByIdRow | null>;
}

const listFilesQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE deleted_at IS NULL\nORDER BY created_at DESC";

export interface ListFilesRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseListFilesRow(row: Record<string, unknown>, ctx: d1_Context): ListFilesRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "itemId": d1_values.rowTextOrNull(row, "item_id", "itemId", ctx),
        "size": d1_values.rowInteger(row, "size", "size", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "hash": d1_values.rowText(row, "hash", "hash", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function listFiles(): QueryDescriptor<ListFilesRow[]> {
    return Object.freeze({
        kind: "many",
        name: "ListFiles",
        sql: listFilesQuery,
        params: Object.freeze([]),
        parse: parseListFilesRow
    }) as unknown as QueryDescriptor<ListFilesRow[]>;
}

const getFileByIdForUserQuery = "SELECT id, user_id, item_id, size, mime_type, hash, upload_url, created_at, updated_at, deleted_at\nFROM files\nWHERE id = ?\n  AND user_id = ?\n  AND deleted_at IS NULL";

export interface GetFileByIdForUserArgs {
    "id": string;
    "userId": string;
}

export interface GetFileByIdForUserRow {
    "id": string;
    "userId": string;
    "itemId": string | null;
    "size": number;
    "mimeType": string;
    "hash": string;
    "uploadUrl": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFileByIdForUserRow(row: Record<string, unknown>, ctx: d1_Context): GetFileByIdForUserRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "itemId": d1_values.rowTextOrNull(row, "item_id", "itemId", ctx),
        "size": d1_values.rowInteger(row, "size", "size", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "hash": d1_values.rowText(row, "hash", "hash", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function getFileByIdForUser(args: GetFileByIdForUserArgs): QueryDescriptor<GetFileByIdForUserRow | null> {
    d1_values.requireArgs(args, "GetFileByIdForUser");
    return Object.freeze({
        kind: "one",
        name: "GetFileByIdForUser",
        sql: getFileByIdForUserQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFileByIdForUser", "id"), d1_values.argText(args["userId"], "GetFileByIdForUser", "userId")]),
        parse: parseGetFileByIdForUserRow
    }) as unknown as QueryDescriptor<GetFileByIdForUserRow | null>;
}

const getItemsWithFilesByFeedIdQuery = "SELECT i.id          as item_id,\n       i.feed_id,\n       i.user_id,\n       i.file_id,\n       i.title       as item_title,\n       i.description as item_description,\n       i.link        as item_link,\n       i.authors     as item_authors,\n       i.published_at,\n       i.created_at  as item_created_at,\n       i.updated_at  as item_updated_at,\n       f.id          as joined_file_id,\n       f.size        as file_size,\n       f.mime_type,\n       f.upload_url\nFROM items i\n         JOIN files f ON i.file_id = f.id\nWHERE i.feed_id = ?\n  AND i.deleted_at IS NULL\n  AND f.deleted_at IS NULL\nORDER BY i.published_at DESC";

export interface GetItemsWithFilesByFeedIdArgs {
    "feedId": string;
}

export interface GetItemsWithFilesByFeedIdRow {
    "itemId": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "itemTitle": string;
    "itemDescription": string;
    "itemLink": string;
    "itemAuthors": string;
    "publishedAt": number;
    "itemCreatedAt": number;
    "itemUpdatedAt": number;
    "joinedFileId": string;
    "fileSize": number;
    "mimeType": string;
    "uploadUrl": string;
}

function parseGetItemsWithFilesByFeedIdRow(row: Record<string, unknown>, ctx: d1_Context): GetItemsWithFilesByFeedIdRow {
    return {
        "itemId": d1_values.rowText(row, "item_id", "itemId", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "itemTitle": d1_values.rowText(row, "item_title", "itemTitle", ctx),
        "itemDescription": d1_values.rowText(row, "item_description", "itemDescription", ctx),
        "itemLink": d1_values.rowText(row, "item_link", "itemLink", ctx),
        "itemAuthors": d1_values.rowText(row, "item_authors", "itemAuthors", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx),
        "itemCreatedAt": d1_values.rowInteger(row, "item_created_at", "itemCreatedAt", ctx),
        "itemUpdatedAt": d1_values.rowInteger(row, "item_updated_at", "itemUpdatedAt", ctx),
        "joinedFileId": d1_values.rowText(row, "joined_file_id", "joinedFileId", ctx),
        "fileSize": d1_values.rowInteger(row, "file_size", "fileSize", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx)
    };
}

export function getItemsWithFilesByFeedId(args: GetItemsWithFilesByFeedIdArgs): QueryDescriptor<GetItemsWithFilesByFeedIdRow[]> {
    d1_values.requireArgs(args, "GetItemsWithFilesByFeedId");
    return Object.freeze({
        kind: "many",
        name: "GetItemsWithFilesByFeedId",
        sql: getItemsWithFilesByFeedIdQuery,
        params: Object.freeze([d1_values.argText(args["feedId"], "GetItemsWithFilesByFeedId", "feedId")]),
        parse: parseGetItemsWithFilesByFeedIdRow
    }) as unknown as QueryDescriptor<GetItemsWithFilesByFeedIdRow[]>;
}

const getItemWithFileByIdQuery = "SELECT i.id          as item_id,\n       i.feed_id,\n       i.user_id,\n       i.file_id,\n       i.title       as item_title,\n       i.description as item_description,\n       i.link        as item_link,\n       i.authors     as item_authors,\n       i.published_at,\n       i.created_at  as item_created_at,\n       i.updated_at  as item_updated_at,\n       f.size        as file_size,\n       f.mime_type,\n       f.upload_url\nFROM items i\n         JOIN files f ON i.file_id = f.id\nWHERE i.id = ?\n  AND i.deleted_at IS NULL\n  AND f.deleted_at IS NULL";

export interface GetItemWithFileByIdArgs {
    "id": string;
}

export interface GetItemWithFileByIdRow {
    "itemId": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "itemTitle": string;
    "itemDescription": string;
    "itemLink": string;
    "itemAuthors": string;
    "publishedAt": number;
    "itemCreatedAt": number;
    "itemUpdatedAt": number;
    "fileSize": number;
    "mimeType": string;
    "uploadUrl": string;
}

function parseGetItemWithFileByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetItemWithFileByIdRow {
    return {
        "itemId": d1_values.rowText(row, "item_id", "itemId", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "itemTitle": d1_values.rowText(row, "item_title", "itemTitle", ctx),
        "itemDescription": d1_values.rowText(row, "item_description", "itemDescription", ctx),
        "itemLink": d1_values.rowText(row, "item_link", "itemLink", ctx),
        "itemAuthors": d1_values.rowText(row, "item_authors", "itemAuthors", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx),
        "itemCreatedAt": d1_values.rowInteger(row, "item_created_at", "itemCreatedAt", ctx),
        "itemUpdatedAt": d1_values.rowInteger(row, "item_updated_at", "itemUpdatedAt", ctx),
        "fileSize": d1_values.rowInteger(row, "file_size", "fileSize", ctx),
        "mimeType": d1_values.rowText(row, "mime_type", "mimeType", ctx),
        "uploadUrl": d1_values.rowText(row, "upload_url", "uploadUrl", ctx)
    };
}

export function getItemWithFileById(args: GetItemWithFileByIdArgs): QueryDescriptor<GetItemWithFileByIdRow | null> {
    d1_values.requireArgs(args, "GetItemWithFileById");
    return Object.freeze({
        kind: "one",
        name: "GetItemWithFileById",
        sql: getItemWithFileByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetItemWithFileById", "id")]),
        parse: parseGetItemWithFileByIdRow
    }) as unknown as QueryDescriptor<GetItemWithFileByIdRow | null>;
}

const getItemByIdQuery = "SELECT id, feed_id, user_id, file_id, title, description, link, authors, created_at, updated_at, deleted_at, published_at\nFROM items\nWHERE id = ?\n  AND feed_id = ?\n  AND deleted_at IS NULL";

export interface GetItemByIdArgs {
    "id": string;
    "feedId": string;
}

export interface GetItemByIdRow {
    "id": string;
    "feedId": string;
    "userId": string;
    "fileId": string;
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
    "publishedAt": number;
}

function parseGetItemByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetItemByIdRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "feedId": d1_values.rowText(row, "feed_id", "feedId", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "fileId": d1_values.rowText(row, "file_id", "fileId", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx),
        "publishedAt": d1_values.rowInteger(row, "published_at", "publishedAt", ctx)
    };
}

export function getItemById(args: GetItemByIdArgs): QueryDescriptor<GetItemByIdRow | null> {
    d1_values.requireArgs(args, "GetItemById");
    return Object.freeze({
        kind: "one",
        name: "GetItemById",
        sql: getItemByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetItemById", "id"), d1_values.argText(args["feedId"], "GetItemById", "feedId")]),
        parse: parseGetItemByIdRow
    }) as unknown as QueryDescriptor<GetItemByIdRow | null>;
}

const getFeedUserByIdQuery = "SELECT user_id\nFROM feeds\nWHERE id = ?\n  AND deleted_at IS NULL";

export interface GetFeedUserByIdArgs {
    "id": string;
}

export interface GetFeedUserByIdRow {
    "userId": string;
}

function parseGetFeedUserByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetFeedUserByIdRow {
    return {
        "userId": d1_values.rowText(row, "user_id", "userId", ctx)
    };
}

export function getFeedUserById(args: GetFeedUserByIdArgs): QueryDescriptor<GetFeedUserByIdRow | null> {
    d1_values.requireArgs(args, "GetFeedUserById");
    return Object.freeze({
        kind: "one",
        name: "GetFeedUserById",
        sql: getFeedUserByIdQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFeedUserById", "id")]),
        parse: parseGetFeedUserByIdRow
    }) as unknown as QueryDescriptor<GetFeedUserByIdRow | null>;
}

const updateItemByIdQuery = "UPDATE items\nSET title        = ?,\n    description  = ?,\n    link         = ?,\n    authors      = ?,\n    published_at = ?,\n    updated_at   = ?\nWHERE id = ?\n  AND feed_id = ?";

export interface UpdateItemByIdArgs {
    "title": string;
    "description": string;
    "link": string;
    "authors": string;
    "publishedAt": number;
    "updatedAt": number;
    "id": string;
    "feedId": string;
}

export function updateItemById(args: UpdateItemByIdArgs): QueryDescriptor<void> {
    d1_values.requireArgs(args, "UpdateItemById");
    return Object.freeze({
        kind: "exec",
        name: "UpdateItemById",
        sql: updateItemByIdQuery,
        params: Object.freeze([d1_values.argText(args["title"], "UpdateItemById", "title"), d1_values.argText(args["description"], "UpdateItemById", "description"), d1_values.argText(args["link"], "UpdateItemById", "link"), d1_values.argText(args["authors"], "UpdateItemById", "authors"), d1_values.argInteger(args["publishedAt"], "UpdateItemById", "publishedAt"), d1_values.argInteger(args["updatedAt"], "UpdateItemById", "updatedAt"), d1_values.argText(args["id"], "UpdateItemById", "id"), d1_values.argText(args["feedId"], "UpdateItemById", "feedId")])
    }) as unknown as QueryDescriptor<void>;
}

const createSampleQuery = "INSERT INTO samples\n(int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null,\n json_value, json_null, any_value, any_null)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\nRETURNING id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null";

export interface CreateSampleArgs {
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": JsonValue;
    "jsonNull": JsonValue | null;
    "anyValue": D1NonNullValue;
    "anyNull": D1Value;
}

export interface CreateSampleRow {
    "id": number;
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": unknown;
    "jsonNull": unknown;
    "anyValue": unknown;
    "anyNull": unknown;
}

function parseCreateSampleRow(row: Record<string, unknown>, ctx: d1_Context): CreateSampleRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "intValue": d1_values.rowInteger(row, "int_value", "intValue", ctx),
        "intNull": d1_values.rowIntegerOrNull(row, "int_null", "intNull", ctx),
        "numValue": d1_values.rowNumber(row, "num_value", "numValue", ctx),
        "numNull": d1_values.rowNumberOrNull(row, "num_null", "numNull", ctx),
        "textValue": d1_values.rowText(row, "text_value", "textValue", ctx),
        "textNull": d1_values.rowTextOrNull(row, "text_null", "textNull", ctx),
        "boolValue": d1_values.rowBoolean(row, "bool_value", "boolValue", ctx),
        "boolNull": d1_values.rowBooleanOrNull(row, "bool_null", "boolNull", ctx),
        "blobValue": d1_values.rowBlob(row, "blob_value", "blobValue", ctx),
        "blobNull": d1_values.rowBlobOrNull(row, "blob_null", "blobNull", ctx),
        "jsonValue": d1_values.rowJson(row, "json_value", "jsonValue", ctx),
        "jsonNull": d1_values.rowJsonOrNull(row, "json_null", "jsonNull", ctx),
        "anyValue": d1_values.rowUnknown(row, "any_value", "anyValue", ctx),
        "anyNull": d1_values.rowUnknownOrNull(row, "any_null", "anyNull", ctx)
    };
}

export function createSample(args: CreateSampleArgs): QueryDescriptor<CreateSampleRow | null> {
    d1_values.requireArgs(args, "CreateSample");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateSample",
        sql: createSampleQuery,
        params: Object.freeze([d1_values.argInteger(args["intValue"], "CreateSample", "intValue"), d1_values.argIntegerOrNull(args["intNull"], "CreateSample", "intNull"), d1_values.argNumber(args["numValue"], "CreateSample", "numValue"), d1_values.argNumberOrNull(args["numNull"], "CreateSample", "numNull"), d1_values.argText(args["textValue"], "CreateSample", "textValue"), d1_values.argTextOrNull(args["textNull"], "CreateSample", "textNull"), d1_values.argBoolean(args["boolValue"], "CreateSample", "boolValue"), d1_values.argBooleanOrNull(args["boolNull"], "CreateSample", "boolNull"), d1_values.argBlob(args["blobValue"], "CreateSample", "blobValue"), d1_values.argBlobOrNull(args["blobNull"], "CreateSample", "blobNull"), d1_values.argJson(args["jsonValue"], "CreateSample", "jsonValue"), d1_values.argJsonOrNull(args["jsonNull"], "CreateSample", "jsonNull"), d1_values.argUnknown(args["anyValue"], "CreateSample", "anyValue"), d1_values.argUnknownOrNull(args["anyNull"], "CreateSample", "anyNull")]),
        parse: parseCreateSampleRow
    }) as unknown as QueryDescriptor<CreateSampleRow | null>;
}

const getSampleByIdQuery = "SELECT id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null\nFROM samples\nWHERE id = ?";

export interface GetSampleByIdArgs {
    "id": number;
}

export interface GetSampleByIdRow {
    "id": number;
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": unknown;
    "jsonNull": unknown;
    "anyValue": unknown;
    "anyNull": unknown;
}

function parseGetSampleByIdRow(row: Record<string, unknown>, ctx: d1_Context): GetSampleByIdRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "intValue": d1_values.rowInteger(row, "int_value", "intValue", ctx),
        "intNull": d1_values.rowIntegerOrNull(row, "int_null", "intNull", ctx),
        "numValue": d1_values.rowNumber(row, "num_value", "numValue", ctx),
        "numNull": d1_values.rowNumberOrNull(row, "num_null", "numNull", ctx),
        "textValue": d1_values.rowText(row, "text_value", "textValue", ctx),
        "textNull": d1_values.rowTextOrNull(row, "text_null", "textNull", ctx),
        "boolValue": d1_values.rowBoolean(row, "bool_value", "boolValue", ctx),
        "boolNull": d1_values.rowBooleanOrNull(row, "bool_null", "boolNull", ctx),
        "blobValue": d1_values.rowBlob(row, "blob_value", "blobValue", ctx),
        "blobNull": d1_values.rowBlobOrNull(row, "blob_null", "blobNull", ctx),
        "jsonValue": d1_values.rowJson(row, "json_value", "jsonValue", ctx),
        "jsonNull": d1_values.rowJsonOrNull(row, "json_null", "jsonNull", ctx),
        "anyValue": d1_values.rowUnknown(row, "any_value", "anyValue", ctx),
        "anyNull": d1_values.rowUnknownOrNull(row, "any_null", "anyNull", ctx)
    };
}

export function getSampleById(args: GetSampleByIdArgs): QueryDescriptor<GetSampleByIdRow | null> {
    d1_values.requireArgs(args, "GetSampleById");
    return Object.freeze({
        kind: "one",
        name: "GetSampleById",
        sql: getSampleByIdQuery,
        params: Object.freeze([d1_values.argInteger(args["id"], "GetSampleById", "id")]),
        parse: parseGetSampleByIdRow
    }) as unknown as QueryDescriptor<GetSampleByIdRow | null>;
}

const listSamplesQuery = "SELECT id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null\nFROM samples\nORDER BY id";

export interface ListSamplesRow {
    "id": number;
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": unknown;
    "jsonNull": unknown;
    "anyValue": unknown;
    "anyNull": unknown;
}

function parseListSamplesRow(row: Record<string, unknown>, ctx: d1_Context): ListSamplesRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "intValue": d1_values.rowInteger(row, "int_value", "intValue", ctx),
        "intNull": d1_values.rowIntegerOrNull(row, "int_null", "intNull", ctx),
        "numValue": d1_values.rowNumber(row, "num_value", "numValue", ctx),
        "numNull": d1_values.rowNumberOrNull(row, "num_null", "numNull", ctx),
        "textValue": d1_values.rowText(row, "text_value", "textValue", ctx),
        "textNull": d1_values.rowTextOrNull(row, "text_null", "textNull", ctx),
        "boolValue": d1_values.rowBoolean(row, "bool_value", "boolValue", ctx),
        "boolNull": d1_values.rowBooleanOrNull(row, "bool_null", "boolNull", ctx),
        "blobValue": d1_values.rowBlob(row, "blob_value", "blobValue", ctx),
        "blobNull": d1_values.rowBlobOrNull(row, "blob_null", "blobNull", ctx),
        "jsonValue": d1_values.rowJson(row, "json_value", "jsonValue", ctx),
        "jsonNull": d1_values.rowJsonOrNull(row, "json_null", "jsonNull", ctx),
        "anyValue": d1_values.rowUnknown(row, "any_value", "anyValue", ctx),
        "anyNull": d1_values.rowUnknownOrNull(row, "any_null", "anyNull", ctx)
    };
}

export function listSamples(): QueryDescriptor<ListSamplesRow[]> {
    return Object.freeze({
        kind: "many",
        name: "ListSamples",
        sql: listSamplesQuery,
        params: Object.freeze([]),
        parse: parseListSamplesRow
    }) as unknown as QueryDescriptor<ListSamplesRow[]>;
}

const createQuirkQuery = "INSERT INTO quirks (id)\nVALUES (?)\nRETURNING id, flag";

export interface CreateQuirkArgs {
    "id": number;
}

export interface CreateQuirkRow {
    "id": number;
    "flag": boolean;
}

function parseCreateQuirkRow(row: Record<string, unknown>, ctx: d1_Context): CreateQuirkRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "flag": d1_values.rowBoolean(row, "flag", "flag", ctx)
    };
}

export function createQuirk(args: CreateQuirkArgs): QueryDescriptor<CreateQuirkRow | null> {
    d1_values.requireArgs(args, "CreateQuirk");
    return Object.freeze({
        kind: "one-insert",
        name: "CreateQuirk",
        sql: createQuirkQuery,
        params: Object.freeze([d1_values.argInteger(args["id"], "CreateQuirk", "id")]),
        parse: parseCreateQuirkRow
    }) as unknown as QueryDescriptor<CreateQuirkRow | null>;
}

const deleteFeedsByUserQuery = "DELETE\nFROM feeds\nWHERE user_id = ?";

export interface DeleteFeedsByUserArgs {
    "userId": string;
}

export function deleteFeedsByUser(args: DeleteFeedsByUserArgs): QueryDescriptor<number> {
    d1_values.requireArgs(args, "DeleteFeedsByUser");
    return Object.freeze({
        kind: "exec-rows",
        name: "DeleteFeedsByUser",
        sql: deleteFeedsByUserQuery,
        params: Object.freeze([d1_values.argText(args["userId"], "DeleteFeedsByUser", "userId")])
    }) as unknown as QueryDescriptor<number>;
}

const insertSampleIdQuery = "INSERT INTO samples\n(int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null,\n json_value, json_null, any_value, any_null)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

export interface InsertSampleIdArgs {
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": JsonValue;
    "jsonNull": JsonValue | null;
    "anyValue": D1NonNullValue;
    "anyNull": D1Value;
}

export function insertSampleId(args: InsertSampleIdArgs): QueryDescriptor<number> {
    d1_values.requireArgs(args, "InsertSampleId");
    return Object.freeze({
        kind: "exec-lastid",
        name: "InsertSampleId",
        sql: insertSampleIdQuery,
        params: Object.freeze([d1_values.argInteger(args["intValue"], "InsertSampleId", "intValue"), d1_values.argIntegerOrNull(args["intNull"], "InsertSampleId", "intNull"), d1_values.argNumber(args["numValue"], "InsertSampleId", "numValue"), d1_values.argNumberOrNull(args["numNull"], "InsertSampleId", "numNull"), d1_values.argText(args["textValue"], "InsertSampleId", "textValue"), d1_values.argTextOrNull(args["textNull"], "InsertSampleId", "textNull"), d1_values.argBoolean(args["boolValue"], "InsertSampleId", "boolValue"), d1_values.argBooleanOrNull(args["boolNull"], "InsertSampleId", "boolNull"), d1_values.argBlob(args["blobValue"], "InsertSampleId", "blobValue"), d1_values.argBlobOrNull(args["blobNull"], "InsertSampleId", "blobNull"), d1_values.argJson(args["jsonValue"], "InsertSampleId", "jsonValue"), d1_values.argJsonOrNull(args["jsonNull"], "InsertSampleId", "jsonNull"), d1_values.argUnknown(args["anyValue"], "InsertSampleId", "anyValue"), d1_values.argUnknownOrNull(args["anyNull"], "InsertSampleId", "anyNull")])
    }) as unknown as QueryDescriptor<number>;
}

const deleteSamplesResultQuery = "DELETE\nFROM samples\nWHERE text_value = ?\nRETURNING id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null";

export interface DeleteSamplesResultArgs {
    "textValue": string;
}

export function deleteSamplesResult(args: DeleteSamplesResultArgs): QueryDescriptor<D1Result<Record<string, unknown>>> {
    d1_values.requireArgs(args, "DeleteSamplesResult");
    return Object.freeze({
        kind: "exec-result",
        name: "DeleteSamplesResult",
        sql: deleteSamplesResultQuery,
        params: Object.freeze([d1_values.argText(args["textValue"], "DeleteSamplesResult", "textValue")])
    }) as unknown as QueryDescriptor<D1Result<Record<string, unknown>>>;
}

const renameFeedsReturningQuery = "UPDATE feeds\nSET title = ?\nWHERE user_id = ?\n  AND deleted_at IS NULL\nRETURNING id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at";

export interface RenameFeedsReturningArgs {
    "title": string;
    "userId": string;
}

export interface RenameFeedsReturningRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseRenameFeedsReturningRow(row: Record<string, unknown>, ctx: d1_Context): RenameFeedsReturningRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function renameFeedsReturning(args: RenameFeedsReturningArgs): QueryDescriptor<RenameFeedsReturningRow | null> {
    d1_values.requireArgs(args, "RenameFeedsReturning");
    return Object.freeze({
        kind: "one",
        name: "RenameFeedsReturning",
        sql: renameFeedsReturningQuery,
        params: Object.freeze([d1_values.argText(args["title"], "RenameFeedsReturning", "title"), d1_values.argText(args["userId"], "RenameFeedsReturning", "userId")]),
        parse: parseRenameFeedsReturningRow
    }) as unknown as QueryDescriptor<RenameFeedsReturningRow | null>;
}

const deleteSamplesReturningQuery = "DELETE\nFROM samples\nWHERE text_value = ?\nRETURNING id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null";

export interface DeleteSamplesReturningArgs {
    "textValue": string;
}

export interface DeleteSamplesReturningRow {
    "id": number;
    "intValue": number;
    "intNull": number | null;
    "numValue": number;
    "numNull": number | null;
    "textValue": string;
    "textNull": string | null;
    "boolValue": boolean;
    "boolNull": boolean | null;
    "blobValue": Uint8Array;
    "blobNull": Uint8Array | null;
    "jsonValue": unknown;
    "jsonNull": unknown;
    "anyValue": unknown;
    "anyNull": unknown;
}

function parseDeleteSamplesReturningRow(row: Record<string, unknown>, ctx: d1_Context): DeleteSamplesReturningRow {
    return {
        "id": d1_values.rowInteger(row, "id", "id", ctx),
        "intValue": d1_values.rowInteger(row, "int_value", "intValue", ctx),
        "intNull": d1_values.rowIntegerOrNull(row, "int_null", "intNull", ctx),
        "numValue": d1_values.rowNumber(row, "num_value", "numValue", ctx),
        "numNull": d1_values.rowNumberOrNull(row, "num_null", "numNull", ctx),
        "textValue": d1_values.rowText(row, "text_value", "textValue", ctx),
        "textNull": d1_values.rowTextOrNull(row, "text_null", "textNull", ctx),
        "boolValue": d1_values.rowBoolean(row, "bool_value", "boolValue", ctx),
        "boolNull": d1_values.rowBooleanOrNull(row, "bool_null", "boolNull", ctx),
        "blobValue": d1_values.rowBlob(row, "blob_value", "blobValue", ctx),
        "blobNull": d1_values.rowBlobOrNull(row, "blob_null", "blobNull", ctx),
        "jsonValue": d1_values.rowJson(row, "json_value", "jsonValue", ctx),
        "jsonNull": d1_values.rowJsonOrNull(row, "json_null", "jsonNull", ctx),
        "anyValue": d1_values.rowUnknown(row, "any_value", "anyValue", ctx),
        "anyNull": d1_values.rowUnknownOrNull(row, "any_null", "anyNull", ctx)
    };
}

export function deleteSamplesReturning(args: DeleteSamplesReturningArgs): QueryDescriptor<DeleteSamplesReturningRow[]> {
    d1_values.requireArgs(args, "DeleteSamplesReturning");
    return Object.freeze({
        kind: "many",
        name: "DeleteSamplesReturning",
        sql: deleteSamplesReturningQuery,
        params: Object.freeze([d1_values.argText(args["textValue"], "DeleteSamplesReturning", "textValue")]),
        parse: parseDeleteSamplesReturningRow
    }) as unknown as QueryDescriptor<DeleteSamplesReturningRow[]>;
}

const getFeedByIdAndUserQuery = "SELECT id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at\nFROM feeds\nWHERE id = ?1\n  AND (user_id = ?2 OR ?2 = '')";

export interface GetFeedByIdAndUserArgs {
    "id": string;
    "userId": string;
}

export interface GetFeedByIdAndUserRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFeedByIdAndUserRow(row: Record<string, unknown>, ctx: d1_Context): GetFeedByIdAndUserRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function getFeedByIdAndUser(args: GetFeedByIdAndUserArgs): QueryDescriptor<GetFeedByIdAndUserRow | null> {
    d1_values.requireArgs(args, "GetFeedByIdAndUser");
    return Object.freeze({
        kind: "one",
        name: "GetFeedByIdAndUser",
        sql: getFeedByIdAndUserQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFeedByIdAndUser", "id"), d1_values.argText(args["userId"], "GetFeedByIdAndUser", "userId")]),
        parse: parseGetFeedByIdAndUserRow
    }) as unknown as QueryDescriptor<GetFeedByIdAndUserRow | null>;
}

const listFeedsByOptionalTitleQuery = "SELECT id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at\nFROM feeds\nWHERE title = ?1\n   OR ?1 IS NULL\nORDER BY id";

export interface ListFeedsByOptionalTitleArgs {
    "title": string | null;
}

export interface ListFeedsByOptionalTitleRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseListFeedsByOptionalTitleRow(row: Record<string, unknown>, ctx: d1_Context): ListFeedsByOptionalTitleRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function listFeedsByOptionalTitle(args: ListFeedsByOptionalTitleArgs): QueryDescriptor<ListFeedsByOptionalTitleRow[]> {
    d1_values.requireArgs(args, "ListFeedsByOptionalTitle");
    return Object.freeze({
        kind: "many",
        name: "ListFeedsByOptionalTitle",
        sql: listFeedsByOptionalTitleQuery,
        params: Object.freeze([d1_values.argTextOrNull(args["title"], "ListFeedsByOptionalTitle", "title")]),
        parse: parseListFeedsByOptionalTitleRow
    }) as unknown as QueryDescriptor<ListFeedsByOptionalTitleRow[]>;
}

const listFeedsByIdsQuery = "SELECT id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at\nFROM feeds\nWHERE id IN (/*SLICE:ids*/?)\nORDER BY id";

export interface ListFeedsByIdsArgs {
    "ids": ReadonlyArray<string>;
}

export interface ListFeedsByIdsRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseListFeedsByIdsRow(row: Record<string, unknown>, ctx: d1_Context): ListFeedsByIdsRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function listFeedsByIds(args: ListFeedsByIdsArgs): QueryDescriptor<ListFeedsByIdsRow[]> {
    d1_values.requireArgs(args, "ListFeedsByIds");
    const d1_slice_ids = d1_values.argSlice(args["ids"], d1_values.argText, "ListFeedsByIds", "ids");
    return Object.freeze({
        kind: "many",
        name: "ListFeedsByIds",
        sql: d1_values.expandSlices(listFeedsByIdsQuery, "ListFeedsByIds", [["/*SLICE:ids*/?", d1_slice_ids.length]]),
        params: Object.freeze([...d1_slice_ids]),
        parse: parseListFeedsByIdsRow
    }) as unknown as QueryDescriptor<ListFeedsByIdsRow[]>;
}

const getFirstFeedByIdsQuery = "SELECT id, user_id, type, title, link, authors, description, created_at, updated_at, deleted_at\nFROM feeds\nWHERE id IN (/*SLICE:ids*/?)\nORDER BY id\nLIMIT 1";

export interface GetFirstFeedByIdsArgs {
    "ids": ReadonlyArray<string>;
}

export interface GetFirstFeedByIdsRow {
    "id": string;
    "userId": string;
    "type": string;
    "title": string;
    "link": string;
    "authors": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;
    "deletedAt": number | null;
}

function parseGetFirstFeedByIdsRow(row: Record<string, unknown>, ctx: d1_Context): GetFirstFeedByIdsRow {
    return {
        "id": d1_values.rowText(row, "id", "id", ctx),
        "userId": d1_values.rowText(row, "user_id", "userId", ctx),
        "type": d1_values.rowText(row, "type", "type", ctx),
        "title": d1_values.rowText(row, "title", "title", ctx),
        "link": d1_values.rowText(row, "link", "link", ctx),
        "authors": d1_values.rowText(row, "authors", "authors", ctx),
        "description": d1_values.rowText(row, "description", "description", ctx),
        "createdAt": d1_values.rowInteger(row, "created_at", "createdAt", ctx),
        "updatedAt": d1_values.rowInteger(row, "updated_at", "updatedAt", ctx),
        "deletedAt": d1_values.rowIntegerOrNull(row, "deleted_at", "deletedAt", ctx)
    };
}

export function getFirstFeedByIds(args: GetFirstFeedByIdsArgs): QueryDescriptor<GetFirstFeedByIdsRow | null> {
    d1_values.requireArgs(args, "GetFirstFeedByIds");
    const d1_slice_ids = d1_values.argSlice(args["ids"], d1_values.argText, "GetFirstFeedByIds", "ids");
    return Object.freeze({
        kind: "one",
        name: "GetFirstFeedByIds",
        sql: d1_values.expandSlices(getFirstFeedByIdsQuery, "GetFirstFeedByIds", [["/*SLICE:ids*/?", d1_slice_ids.length]]),
        params: Object.freeze([...d1_slice_ids]),
        parse: parseGetFirstFeedByIdsRow
    }) as unknown as QueryDescriptor<GetFirstFeedByIdsRow | null>;
}

const touchFeedsByIdsQuery = "UPDATE feeds\nSET updated_at = ?\nWHERE id IN (/*SLICE:ids*/?)";

export interface TouchFeedsByIdsArgs {
    "updatedAt": number;
    "ids": ReadonlyArray<string>;
}

export function touchFeedsByIds(args: TouchFeedsByIdsArgs): QueryDescriptor<void> {
    d1_values.requireArgs(args, "TouchFeedsByIds");
    const d1_slice_ids = d1_values.argSlice(args["ids"], d1_values.argText, "TouchFeedsByIds", "ids");
    return Object.freeze({
        kind: "exec",
        name: "TouchFeedsByIds",
        sql: d1_values.expandSlices(touchFeedsByIdsQuery, "TouchFeedsByIds", [["/*SLICE:ids*/?", d1_slice_ids.length]]),
        params: Object.freeze([d1_values.argInteger(args["updatedAt"], "TouchFeedsByIds", "updatedAt"), ...d1_slice_ids])
    }) as unknown as QueryDescriptor<void>;
}

const deleteFeedsByIdsForUserQuery = "DELETE\nFROM feeds\nWHERE user_id = ?\n  AND id IN (/*SLICE:ids*/?)";

export interface DeleteFeedsByIdsForUserArgs {
    "userId": string;
    "ids": ReadonlyArray<string>;
}

export function deleteFeedsByIdsForUser(args: DeleteFeedsByIdsForUserArgs): QueryDescriptor<number> {
    d1_values.requireArgs(args, "DeleteFeedsByIdsForUser");
    const d1_slice_ids = d1_values.argSlice(args["ids"], d1_values.argText, "DeleteFeedsByIdsForUser", "ids");
    return Object.freeze({
        kind: "exec-rows",
        name: "DeleteFeedsByIdsForUser",
        sql: d1_values.expandSlices(deleteFeedsByIdsForUserQuery, "DeleteFeedsByIdsForUser", [["/*SLICE:ids*/?", d1_slice_ids.length]]),
        params: Object.freeze([d1_values.argText(args["userId"], "DeleteFeedsByIdsForUser", "userId"), ...d1_slice_ids])
    }) as unknown as QueryDescriptor<number>;
}

const deleteSamplesByTextValuesQuery = "DELETE\nFROM samples\nWHERE text_value IN (/*SLICE:values*/?)\nRETURNING id, int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null, json_value, json_null, any_value, any_null";

export interface DeleteSamplesByTextValuesArgs {
    "values": ReadonlyArray<string>;
}

export function deleteSamplesByTextValues(args: DeleteSamplesByTextValuesArgs): QueryDescriptor<D1Result<Record<string, unknown>>> {
    d1_values.requireArgs(args, "DeleteSamplesByTextValues");
    const d1_slice_values = d1_values.argSlice(args["values"], d1_values.argText, "DeleteSamplesByTextValues", "values");
    return Object.freeze({
        kind: "exec-result",
        name: "DeleteSamplesByTextValues",
        sql: d1_values.expandSlices(deleteSamplesByTextValuesQuery, "DeleteSamplesByTextValues", [["/*SLICE:values*/?", d1_slice_values.length]]),
        params: Object.freeze([...d1_slice_values])
    }) as unknown as QueryDescriptor<D1Result<Record<string, unknown>>>;
}

const copySampleForTextValuesQuery = "INSERT INTO samples\n(int_value, int_null, num_value, num_null, text_value, text_null, bool_value, bool_null, blob_value, blob_null,\n json_value, json_null, any_value, any_null)\nSELECT s.int_value,\n       s.int_null,\n       s.num_value,\n       s.num_null,\n       ?,\n       s.text_null,\n       s.bool_value,\n       s.bool_null,\n       s.blob_value,\n       s.blob_null,\n       s.json_value,\n       s.json_null,\n       s.any_value,\n       s.any_null\nFROM samples s\nWHERE s.text_value IN (/*SLICE:values*/?)\nORDER BY s.id\nLIMIT 1";

export interface CopySampleForTextValuesArgs {
    "textValue": string;
    "values": ReadonlyArray<string>;
}

export function copySampleForTextValues(args: CopySampleForTextValuesArgs): QueryDescriptor<number> {
    d1_values.requireArgs(args, "CopySampleForTextValues");
    const d1_slice_values = d1_values.argSlice(args["values"], d1_values.argText, "CopySampleForTextValues", "values");
    return Object.freeze({
        kind: "exec-lastid",
        name: "CopySampleForTextValues",
        sql: d1_values.expandSlices(copySampleForTextValuesQuery, "CopySampleForTextValues", [["/*SLICE:values*/?", d1_slice_values.length]]),
        params: Object.freeze([d1_values.argText(args["textValue"], "CopySampleForTextValues", "textValue"), ...d1_slice_values])
    }) as unknown as QueryDescriptor<number>;
}

const getFeedAndItemEmbedQuery = "SELECT f.id AS \"d1_embed_0_0\", f.user_id AS \"d1_embed_0_1\", f.type AS \"d1_embed_0_2\", f.title AS \"d1_embed_0_3\", f.link AS \"d1_embed_0_4\", f.authors AS \"d1_embed_0_5\", f.description AS \"d1_embed_0_6\", f.created_at AS \"d1_embed_0_7\", f.updated_at AS \"d1_embed_0_8\", f.deleted_at AS \"d1_embed_0_9\", i.id AS \"d1_embed_1_0\", i.feed_id AS \"d1_embed_1_1\", i.user_id AS \"d1_embed_1_2\", i.file_id AS \"d1_embed_1_3\", i.title AS \"d1_embed_1_4\", i.description AS \"d1_embed_1_5\", i.link AS \"d1_embed_1_6\", i.authors AS \"d1_embed_1_7\", i.created_at AS \"d1_embed_1_8\", i.updated_at AS \"d1_embed_1_9\", i.deleted_at AS \"d1_embed_1_10\", i.published_at AS \"d1_embed_1_11\"\nFROM feeds f\n         JOIN items i ON i.feed_id = f.id\nWHERE i.id = ?";

export interface GetFeedAndItemEmbedArgs {
    "id": string;
}

export interface GetFeedAndItemEmbedRow {
    "feeds": {
        "id": string;
        "userId": string;
        "type": string;
        "title": string;
        "link": string;
        "authors": string;
        "description": string;
        "createdAt": number;
        "updatedAt": number;
        "deletedAt": number | null;
    };
    "items": {
        "id": string;
        "feedId": string;
        "userId": string;
        "fileId": string;
        "title": string;
        "description": string;
        "link": string;
        "authors": string;
        "createdAt": number;
        "updatedAt": number;
        "deletedAt": number | null;
        "publishedAt": number;
    };
}

function parseGetFeedAndItemEmbedRow(row: Record<string, unknown>, ctx: d1_Context): GetFeedAndItemEmbedRow {
    return {
        "feeds": {
            "id": d1_values.rowText(row, "d1_embed_0_0", "feeds.id", ctx),
            "userId": d1_values.rowText(row, "d1_embed_0_1", "feeds.userId", ctx),
            "type": d1_values.rowText(row, "d1_embed_0_2", "feeds.type", ctx),
            "title": d1_values.rowText(row, "d1_embed_0_3", "feeds.title", ctx),
            "link": d1_values.rowText(row, "d1_embed_0_4", "feeds.link", ctx),
            "authors": d1_values.rowText(row, "d1_embed_0_5", "feeds.authors", ctx),
            "description": d1_values.rowText(row, "d1_embed_0_6", "feeds.description", ctx),
            "createdAt": d1_values.rowInteger(row, "d1_embed_0_7", "feeds.createdAt", ctx),
            "updatedAt": d1_values.rowInteger(row, "d1_embed_0_8", "feeds.updatedAt", ctx),
            "deletedAt": d1_values.rowIntegerOrNull(row, "d1_embed_0_9", "feeds.deletedAt", ctx)
        },
        "items": {
            "id": d1_values.rowText(row, "d1_embed_1_0", "items.id", ctx),
            "feedId": d1_values.rowText(row, "d1_embed_1_1", "items.feedId", ctx),
            "userId": d1_values.rowText(row, "d1_embed_1_2", "items.userId", ctx),
            "fileId": d1_values.rowText(row, "d1_embed_1_3", "items.fileId", ctx),
            "title": d1_values.rowText(row, "d1_embed_1_4", "items.title", ctx),
            "description": d1_values.rowText(row, "d1_embed_1_5", "items.description", ctx),
            "link": d1_values.rowText(row, "d1_embed_1_6", "items.link", ctx),
            "authors": d1_values.rowText(row, "d1_embed_1_7", "items.authors", ctx),
            "createdAt": d1_values.rowInteger(row, "d1_embed_1_8", "items.createdAt", ctx),
            "updatedAt": d1_values.rowInteger(row, "d1_embed_1_9", "items.updatedAt", ctx),
            "deletedAt": d1_values.rowIntegerOrNull(row, "d1_embed_1_10", "items.deletedAt", ctx),
            "publishedAt": d1_values.rowInteger(row, "d1_embed_1_11", "items.publishedAt", ctx)
        }
    };
}

export function getFeedAndItemEmbed(args: GetFeedAndItemEmbedArgs): QueryDescriptor<GetFeedAndItemEmbedRow | null> {
    d1_values.requireArgs(args, "GetFeedAndItemEmbed");
    return Object.freeze({
        kind: "one",
        name: "GetFeedAndItemEmbed",
        sql: getFeedAndItemEmbedQuery,
        params: Object.freeze([d1_values.argText(args["id"], "GetFeedAndItemEmbed", "id")]),
        parse: parseGetFeedAndItemEmbedRow
    }) as unknown as QueryDescriptor<GetFeedAndItemEmbedRow | null>;
}

const listItemsWithNotesQuery = "SELECT i.id AS item_id, n.item_id AS \"d1_embed_0_0\", n.note AS \"d1_embed_0_1\", n.rating AS \"d1_embed_0_2\"\nFROM items i\n         LEFT JOIN item_notes n ON n.item_id = i.id\nWHERE i.feed_id = ?\nORDER BY i.id";

export interface ListItemsWithNotesArgs {
    "feedId": string;
}

export interface ListItemsWithNotesRow {
    "itemId": string;
    "itemNotes": {
        "itemId": string | null;
        "note": string | null;
        "rating": number | null;
    };
}

function parseListItemsWithNotesRow(row: Record<string, unknown>, ctx: d1_Context): ListItemsWithNotesRow {
    return {
        "itemId": d1_values.rowText(row, "item_id", "itemId", ctx),
        "itemNotes": {
            "itemId": d1_values.rowTextOrNull(row, "d1_embed_0_0", "itemNotes.itemId", ctx),
            "note": d1_values.rowTextOrNull(row, "d1_embed_0_1", "itemNotes.note", ctx),
            "rating": d1_values.rowIntegerOrNull(row, "d1_embed_0_2", "itemNotes.rating", ctx)
        }
    };
}

export function listItemsWithNotes(args: ListItemsWithNotesArgs): QueryDescriptor<ListItemsWithNotesRow[]> {
    d1_values.requireArgs(args, "ListItemsWithNotes");
    return Object.freeze({
        kind: "many",
        name: "ListItemsWithNotes",
        sql: listItemsWithNotesQuery,
        params: Object.freeze([d1_values.argText(args["feedId"], "ListItemsWithNotes", "feedId")]),
        parse: parseListItemsWithNotesRow
    }) as unknown as QueryDescriptor<ListItemsWithNotesRow[]>;
}

const listItemsWithFilesByIdsQuery = "SELECT i.id AS \"d1_embed_0_0\", i.feed_id AS \"d1_embed_0_1\", i.user_id AS \"d1_embed_0_2\", i.file_id AS \"d1_embed_0_3\", i.title AS \"d1_embed_0_4\", i.description AS \"d1_embed_0_5\", i.link AS \"d1_embed_0_6\", i.authors AS \"d1_embed_0_7\", i.created_at AS \"d1_embed_0_8\", i.updated_at AS \"d1_embed_0_9\", i.deleted_at AS \"d1_embed_0_10\", i.published_at AS \"d1_embed_0_11\", fl.id AS \"d1_embed_1_0\", fl.user_id AS \"d1_embed_1_1\", fl.item_id AS \"d1_embed_1_2\", fl.size AS \"d1_embed_1_3\", fl.mime_type AS \"d1_embed_1_4\", fl.hash AS \"d1_embed_1_5\", fl.upload_url AS \"d1_embed_1_6\", fl.created_at AS \"d1_embed_1_7\", fl.updated_at AS \"d1_embed_1_8\", fl.deleted_at AS \"d1_embed_1_9\"\nFROM items i\n         JOIN files fl ON i.file_id = fl.id\nWHERE i.id IN (/*SLICE:ids*/?)\nORDER BY i.id";

export interface ListItemsWithFilesByIdsArgs {
    "ids": ReadonlyArray<string>;
}

export interface ListItemsWithFilesByIdsRow {
    "items": {
        "id": string;
        "feedId": string;
        "userId": string;
        "fileId": string;
        "title": string;
        "description": string;
        "link": string;
        "authors": string;
        "createdAt": number;
        "updatedAt": number;
        "deletedAt": number | null;
        "publishedAt": number;
    };
    "files": {
        "id": string;
        "userId": string;
        "itemId": string | null;
        "size": number;
        "mimeType": string;
        "hash": string;
        "uploadUrl": string;
        "createdAt": number;
        "updatedAt": number;
        "deletedAt": number | null;
    };
}

function parseListItemsWithFilesByIdsRow(row: Record<string, unknown>, ctx: d1_Context): ListItemsWithFilesByIdsRow {
    return {
        "items": {
            "id": d1_values.rowText(row, "d1_embed_0_0", "items.id", ctx),
            "feedId": d1_values.rowText(row, "d1_embed_0_1", "items.feedId", ctx),
            "userId": d1_values.rowText(row, "d1_embed_0_2", "items.userId", ctx),
            "fileId": d1_values.rowText(row, "d1_embed_0_3", "items.fileId", ctx),
            "title": d1_values.rowText(row, "d1_embed_0_4", "items.title", ctx),
            "description": d1_values.rowText(row, "d1_embed_0_5", "items.description", ctx),
            "link": d1_values.rowText(row, "d1_embed_0_6", "items.link", ctx),
            "authors": d1_values.rowText(row, "d1_embed_0_7", "items.authors", ctx),
            "createdAt": d1_values.rowInteger(row, "d1_embed_0_8", "items.createdAt", ctx),
            "updatedAt": d1_values.rowInteger(row, "d1_embed_0_9", "items.updatedAt", ctx),
            "deletedAt": d1_values.rowIntegerOrNull(row, "d1_embed_0_10", "items.deletedAt", ctx),
            "publishedAt": d1_values.rowInteger(row, "d1_embed_0_11", "items.publishedAt", ctx)
        },
        "files": {
            "id": d1_values.rowText(row, "d1_embed_1_0", "files.id", ctx),
            "userId": d1_values.rowText(row, "d1_embed_1_1", "files.userId", ctx),
            "itemId": d1_values.rowTextOrNull(row, "d1_embed_1_2", "files.itemId", ctx),
            "size": d1_values.rowInteger(row, "d1_embed_1_3", "files.size", ctx),
            "mimeType": d1_values.rowText(row, "d1_embed_1_4", "files.mimeType", ctx),
            "hash": d1_values.rowText(row, "d1_embed_1_5", "files.hash", ctx),
            "uploadUrl": d1_values.rowText(row, "d1_embed_1_6", "files.uploadUrl", ctx),
            "createdAt": d1_values.rowInteger(row, "d1_embed_1_7", "files.createdAt", ctx),
            "updatedAt": d1_values.rowInteger(row, "d1_embed_1_8", "files.updatedAt", ctx),
            "deletedAt": d1_values.rowIntegerOrNull(row, "d1_embed_1_9", "files.deletedAt", ctx)
        }
    };
}

export function listItemsWithFilesByIds(args: ListItemsWithFilesByIdsArgs): QueryDescriptor<ListItemsWithFilesByIdsRow[]> {
    d1_values.requireArgs(args, "ListItemsWithFilesByIds");
    const d1_slice_ids = d1_values.argSlice(args["ids"], d1_values.argText, "ListItemsWithFilesByIds", "ids");
    return Object.freeze({
        kind: "many",
        name: "ListItemsWithFilesByIds",
        sql: d1_values.expandSlices(listItemsWithFilesByIdsQuery, "ListItemsWithFilesByIds", [["/*SLICE:ids*/?", d1_slice_ids.length]]),
        params: Object.freeze([...d1_slice_ids]),
        parse: parseListItemsWithFilesByIdsRow
    }) as unknown as QueryDescriptor<ListItemsWithFilesByIdsRow[]>;
}
