import { Column, File, GenerateRequest, GenerateResponse } from "./gen/plugin/codegen_pb";
import { Driver as D1Driver } from "./d1";
import { planEmission, type QueryPlan } from "./emission-plan";
import { validateGenerateRequest, type ValidatedGeneration } from "./validation";

type Options = ValidatedGeneration["options"];

interface Driver {
  runtimeCode(): string;
  columnType(column?: Column): string;
  parseFnDecl(funcName: string, returnIface: string, fields: QueryPlan["rowFields"]): string;
  factoryDecl(plan: QueryPlan): string;
}

function createDriver(options: Options): Driver {
  switch (options.interface) {
    case "workers": return new D1Driver();
  }
}

export function generate(input: GenerateRequest): GenerateResponse {
  return generateValidated(validateGenerateRequest(input));
}

export function generateValidated(validated: ValidatedGeneration): GenerateResponse {
  const driver = createDriver(validated.options);
  const plan = planEmission(validated);
  const encoder = new TextEncoder();
  const files: File[] = [new File({
    name: plan.runtime.outputPath,
    contents: encoder.encode(driver.runtimeCode()),
  })];
  for (const module of plan.queryModules) {
    const nodes: string[] = [];
    for (const query of module.queries) {
      nodes.push(`const ${query.sqlConstantName} = ${query.sqlLiteral};`);
      if (query.argsTypeName) nodes.push(interfaceDecl(query.argsTypeName, query.argumentFields, driver));
      if (query.rowTypeName) nodes.push(interfaceDecl(query.rowTypeName, query.rowFields, driver));
      if (query.parserName && query.rowTypeName) nodes.push(driver.parseFnDecl(query.parserName, query.rowTypeName, query.rowFields));
      nodes.push(driver.factoryDecl(query));
    }
    let source = "// Code generated by sqlc. DO NOT EDIT.\n\n";
    if (module.runtimeTypeImports.length > 0) {
      source += `import type { ${module.runtimeTypeImports.join(", ")} } from ${module.runtimeSpecifierLiteral};\n\n`;
    }
    source += nodes.map((node) => `${node}\n`).join("\n");
    files.push(new File({ name: module.outputPath, contents: encoder.encode(source) }));
  }
  return new GenerateResponse({ files });
}

function interfaceDecl(
  name: string,
  fields: readonly { publicNameLiteral: string; column: Column }[],
  driver: Driver,
): string {
  const body = fields.map((field) => `    ${field.publicNameLiteral}: ${driver.columnType(field.column)}`).join(";\n");
  return `export interface ${name} {\n${body};\n}`;
}
