import { File, GenerateRequest, GenerateResponse } from "./gen/plugin/codegen_pb";
import { Driver as D1Driver } from "./d1";
import { planEmission, RUNTIME_VALUE_ALIAS, type ArgumentFieldPlan, type QueryPlan, type RowFieldPlan } from "./emission-plan";
import { validateGenerateRequest, type ValidatedGeneration } from "./validation";

type Options = ValidatedGeneration["options"];

interface Driver {
  runtimeCode(): string;
  resultContextDecl(): string;
  argumentType(field: ArgumentFieldPlan): string;
  rowType(field: RowFieldPlan): string;
  parseFnDecl(funcName: string, returnIface: string, fields: readonly RowFieldPlan[]): string;
  factoryDecl(plan: QueryPlan): string;
}

function createDriver(options: Options): Driver {
  switch (options.interface) {
    case "workers": return new D1Driver();
  }
}

export function generate(input: GenerateRequest): GenerateResponse {
  return generateValidated(validateGenerateRequest(input));
}

export function generateValidated(validated: ValidatedGeneration): GenerateResponse {
  const driver = createDriver(validated.options);
  const plan = planEmission(validated);
  const encoder = new TextEncoder();
  const files: File[] = [new File({
    name: plan.runtime.outputPath,
    contents: encoder.encode(driver.runtimeCode()),
  })];
  for (const module of plan.queryModules) {
    const nodes: string[] = [];
    for (const query of module.queries) {
      nodes.push(`const ${query.sqlConstantName} = ${query.sqlLiteral};`);
      if (query.argsTypeName) nodes.push(interfaceDecl(query.argsTypeName, query.argumentFields, (field) => driver.argumentType(field)));
      if (query.rowTypeName) nodes.push(interfaceDecl(query.rowTypeName, query.rowFields, (field) => driver.rowType(field)));
      if (query.parserName && query.rowTypeName) nodes.push(driver.parseFnDecl(query.parserName, query.rowTypeName, query.rowFields));
      nodes.push(driver.factoryDecl(query));
    }
    let source = "// Code generated by sqlc. DO NOT EDIT.\n\n";
    const importLines: string[] = [];
    if (module.runtimeValueImports.length > 0) {
      importLines.push(`import { generatedInternals as ${RUNTIME_VALUE_ALIAS} } from ${module.runtimeSpecifierLiteral};`);
    }
    if (module.runtimeTypeImports.length > 0) {
      importLines.push(`import type { ${module.runtimeTypeImports.join(", ")} } from ${module.runtimeSpecifierLiteral};`);
    }
    if (importLines.length > 0) source += `${importLines.join("\n")}\n\n`;
    if (module.emitsResultContext) source += `${driver.resultContextDecl()}\n\n`;
    source += nodes.map((node) => `${node}\n`).join("\n");
    files.push(new File({ name: module.outputPath, contents: encoder.encode(source) }));
  }
  return new GenerateResponse({ files });
}

function interfaceDecl<Field extends { publicNameLiteral: string }>(
  name: string,
  fields: readonly Field[],
  spell: (field: Field) => string,
): string {
  const body = fields.map((field) => `    ${field.publicNameLiteral}: ${spell(field)}`).join(";\n");
  return `export interface ${name} {\n${body};\n}`;
}
