import {
  GenerateRequest,
  GenerateResponse,
  Parameter,
  Column,
  File,
  Query,
} from "./gen/plugin/codegen_pb";

import { argName, colName } from "./utils";
import { Driver as D1Driver } from "./d1";

interface Options {
  interface?: "workers";
}

interface Driver {
  runtimeCode: () => string;
  columnType: (c?: Column) => string;
  parseFnDecl: (funcName: string, returnIface: string, columns: Column[]) => string;
  execDecl: (funcName: string, queryName: string, argIface: string | undefined, params: Parameter[]) => string;
  oneDecl: (funcName: string, queryName: string, argIface: string | undefined, returnIface: string, parseFnName: string, params: Parameter[]) => string;
  oneInsertDecl: (funcName: string, queryName: string, argIface: string | undefined, returnIface: string, parseFnName: string, params: Parameter[]) => string;
  manyDecl: (funcName: string, queryName: string, argIface: string | undefined, returnIface: string, parseFnName: string, params: Parameter[]) => string;
}

function createDriver(options: Options): Driver {
  switch (options.interface) {
    case "workers":
      return new D1Driver();
  }
  throw new Error(`unknown interface: ${options.interface}`);
}

export function generate(input: GenerateRequest): GenerateResponse {
  const files: File[] = [];
  let options: Options = {};

  if (input.pluginOptions.length > 0) {
    options = JSON.parse(new TextDecoder().decode(input.pluginOptions)) as Options;
  }

  const driver = createDriver(options);
  const queryMap = new Map<string, Query[]>();

  for (const query of input.queries) {
    const queries = queryMap.get(query.filename) ?? [];
    queries.push(query);
    queryMap.set(query.filename, queries);
  }

  for (const [filename, queries] of queryMap.entries()) {
    const nodes: string[] = [];

    for (const query of queries) {
      const columnNames = new Set<string>();
      for (const column of query.columns) {
        if (!column.name) continue;
        if (columnNames.has(column.name)) {
          throw new Error(
            `query ${query.name} returns duplicate column ${column.name}; ` +
              "D1 object rows require unique output names, so add a unique SQL alias"
          );
        }
        columnNames.add(column.name);
      }

      const lowerName = query.name[0].toLowerCase() + query.name.slice(1);
      const textName = `${lowerName}Query`;
      nodes.push(queryDecl(textName, `-- name: ${query.name} ${query.cmd}\n${query.text}`));

      let argIface: string | undefined;
      let returnIface: string | undefined;
      let parseFnName: string | undefined;
      if (query.params.length > 0) {
        argIface = `${query.name}Args`;
        nodes.push(argsDecl(argIface, driver, query.params));
      }
      if (query.columns.length > 0) {
        returnIface = `${query.name}Row`;
        parseFnName = `parse${query.name}Row`;
        nodes.push(rowDecl(returnIface, driver, query.columns));
        nodes.push(driver.parseFnDecl(parseFnName, returnIface, query.columns));
      }

      switch (query.cmd) {
        case ":exec":
          nodes.push(driver.execDecl(lowerName, textName, argIface, query.params));
          break;
        case ":one":
          if (query.insertIntoTable) {
            nodes.push(driver.oneInsertDecl(lowerName, textName, argIface, returnIface ?? "void", parseFnName ?? "", query.params));
          } else {
            nodes.push(driver.oneDecl(lowerName, textName, argIface, returnIface ?? "void", parseFnName ?? "", query.params));
          }
          break;
        case ":many":
          nodes.push(driver.manyDecl(lowerName, textName, argIface, returnIface ?? "void", parseFnName ?? "", query.params));
          break;
      }
    }

    files.push(new File({
      name: `${filename.replace(".", "_")}.ts`,
      contents: new TextEncoder().encode(printNode(driver, nodes)),
    }));
  }

  return new GenerateResponse({ files });
}

function queryDecl(name: string, sql: string): string {
  return `const ${name} = \`${sql}\`;`;
}

function argsDecl(name: string, driver: Driver, params: Parameter[]): string {
  const fields = params.map((param, i) => {
    const fieldName = argName(i, param.column);
    const type = driver.columnType(param.column);
    return `    ${fieldName}: ${type}`;
  }).join(";\n");
  return `export interface ${name} {\n${fields};\n}`;
}

function rowDecl(name: string, driver: Driver, columns: Column[]): string {
  const fields = columns.map((column, i) => {
    const fieldName = colName(i, column);
    const type = driver.columnType(column);
    return `    ${fieldName}: ${type}`;
  }).join(";\n");
  return `export interface ${name} {\n${fields};\n}`;
}

function printNode(driver: Driver, nodes: string[]): string {
  let output = "// Code generated by sqlc. DO NOT EDIT.\n\n";
  output += driver.runtimeCode();
  output += "\n";
  for (const node of nodes) output += `${node}\n\n`;
  return output;
}
